### ISSUE TITLE
Question/proposition to add `gwt:codeserver-no-fork` goal

### ISSUE THREAD

**Issue by azatsarynnyy** [tbroyer/gwt-maven-plugin#100]
Hello Thomas!
I'm working on a large GWT app project where launching `gwt:codeserver` takes several minutes. After reducing the projects list with the `-pl` + `-am` parameters, maven reactor includes >40 gwt-libs + some shared libs.
In my case, `process-classes` build phase execution is redundant since my sources are already built before launching SDM in 99% of cases. But a lot of sources are generated during maven build.

So my question is do you have any plans for adding a mojo for launching CodeServer w/o forking a `process-classes` build phase (e.g. jar-no-fork)?

P.S.: I've tried to do it myself and CodeServer starts in ~10 sec. The only thing that needed to be fixed in my case is adding the generated sources directories (e.g. `target/generated-sources`) to the maven's `CompileSourceRoots`  in order to [pass it](https://github.com/azatsarynnyy/gwt-maven-plugin/blob/d45999f3c3d053fc66435455817931c32899bf31/src/main/java/net/ltgt/gwt/maven/AbstractDevModeMojo.java#L254) to the `-src` CodeServer's parameter.

**Comment by azatsarynnyy** [comment]
You are absolutely right! In my case, there are a lot of redundant (in terms of SDM) goals are bound to the build. But only `build-helper-maven-plugin` performs useful work: adds the generated (re-)sources to the *compile source roots*. Skipping all the remaining goals gives an acceptable launch time - `<1 min.` instead of `>3min.`
Consequently, there's no need to bypass the `process-classes` build phase.

Sorry for disturbing and many thanks for pointing this out.
I'm very grateful for your help!

**Comment by tbroyer** [comment]
You're welcome; always happy to get things done by not doing :slightly_smiling_face:
