### ISSUE TITLE
How to run gwt on an external HTTPS server?

### ISSUE THREAD

**Issue by pedy711** [tbroyer/gwt-maven-plugin#101]
I have SmartGWT as my GUI and Spring Boot as my server side code. They both work fine when running on HTTP, but when I configured SSL on my Spring Boot server, Smartgwt gives the following error:

Couldn't load app from Super Dev Mode. server at http://192.168.56.1:9876. Please make sure this server is ready. Do you want to try again?

I am using gwt-maven-plugin net.ltgt.gwt.maven. I am also using followings in the configuration file in maven file:

<devmodeArg>-noserver</devmodeArg>
<arg>-bindAddress</arg>
<arg>0.0.0.0</arg>

**Comment by tbroyer** [comment]
See https://github.com/gwtproject/gwt/issues/7535
