### ISSUE TITLE
Did not work w/o moduleShortName in eclipse after update to rc-9 from rc-7

### ISSUE THREAD

**Issue by foal** [tbroyer/gwt-maven-plugin#102]
W/o moduleShortName (wrong):
![image](https://user-images.githubusercontent.com/458209/33516450-455ea352-d773-11e7-9797-a31c3c9f9b4f.png)

With moduleShortName:
![image](https://user-images.githubusercontent.com/458209/33516470-7f70e712-d773-11e7-98d9-7ef3f4db6a93.png)

Before an update (rc-7), it works without moduleShortName.

**Comment by tbroyer** [comment]
This must be a bug in the GWT Eclipse Plugin, not gwt-maven-plugin: https://github.com/gwt-plugins/gwt-eclipse-plugin
