### ISSUE TITLE
Consider GWT module xml source tags to source roots filter for up-to-date check 

### ISSUE THREAD

**Issue by littlewing88** [tbroyer/gwt-maven-plugin#104]
Hi, 
looking at the sources of the plugin (CompileMojo) it seems that all the sources in a project are considered in the up-to-date check for gwt compilation.
```
List<String> sourceRoots = SourcesAsResourcesHelper.filterSourceRoots(
        getLog(), project.getResources(), project.getCompileSourceRoots());

    if (!forceCompilation && !isStale(sourceRoots)) {
      getLog().info("Compilation output seems uptodate. GWT compilation skipped.");
      return;
    }
```
As far as I know, only paths declared in the gwt.xml module with `<source path="" />` tag (if any is declared) are taken into consideration from the gwt compiler.

Is it possibile to achieve the same behaviour or configure that somehow without having to split in different modules the source folder?

Thanks in advice!

**Comment by tbroyer** [comment]
> Is it possibile to achieve the same behaviour or configure that somehow without having to split in different modules the source folder?

No it's not. If you know what should happen, you can invoke Maven with `-Dgwt.skipCompilation` to skip the GWT compilation (or `-Dgwt.forceCompilation` to force it)

> As far as I know, only paths declared in the gwt.xml module with `<source path="" />` tag (if any is declared) are taken into consideration from the gwt compiler.

It's actually not that simple: generators and linkers also influence the output, as well as resources in client bundles or UiBinder, or in `<public path=""/>`.

I don't want to add that feature to the plugin as it would require duplicating the resource loading mechanism of GWT, or loading GWT classes reflectively, and with little to no guarantee on forward compatibility of those (mostly internal) APIs; and that still wouldn't account for resources.
