### ISSUE TITLE
guava-gwt and super-source location

### ISSUE THREAD

**Issue by shauntarves** [tbroyer/gwt-maven-plugin#111]
When running in super dev mode with this plugin, my application is not able to resolve the location of a super-sourced file from a third-party module (guava-gwt) that I inherit.

Note that using the standard compile mojo doesn't appear to create this issue, only the codeserver - but it could very well just be different configuration options

In this case, Guava's `Platform.java` is on the runtime classpath (sourcemaps) under com/google/common/base/super/com/google/common/base. I'm not entirely sure what value needs to be modified to relocate the super sources to the proper `com/google/common/base`. Since I don't control this module, how am I able to fix this?

![40386068-b5aaf324-5dd6-11e8-9775-2c2ea6b04141](https://user-images.githubusercontent.com/4731056/40440817-152ff0a4-5e8d-11e8-8505-380613b9d3e6.png)

**Comment by tbroyer** [comment]
The source does not need to be "relocated". If/as you see the source file in source maps, it means its correctly passed to the CodeServer by the plugin; that's where the plugin's responsibility ends. What you're experiencing then looks like a bug in GWT proper.

To be sure, run Maven with debug logs (`mvn -X`) and look for the `Classpath:` and `Arguments:` lines. This should enable you to a) verify the values and b) run the CodeServer independently of Maven.
If the values look OK, then it's a bug in GWT proper.

**Comment by tbroyer** [comment]
> Who/what mechanism is responsible for taking the sources that are basically "an extra hierarchy deep" and putting them in the correct place?

It's GWT, processing the `<super-source path="…" />` declarations: see http://www.gwtproject.org/doc/latest/DevGuideOrganizingProjects.html#DevGuideModuleXml and https://github.com/gwtproject/old_google_code_wiki/blob/master/ResourceOracle.wiki.md

Here, the `com.google.common.base.Base` module supersources the `com.google.common.base.Platform` class inside the `super` subpackage/subfolder.

I suppose you have a `<super-source path="jre"/>` in your module, telling GWT that you're super-sourcing `java.util.UUID` inside the `jre` subpackage/subfolder.

**Comment by shauntarves** [comment]
Yes, I do have the `<super-source path="jre"/>` in my module, and all is good with that one. The one thing that causes me concern is this note I read at http://www.gwtproject.org/doc/latest/DevGuideOrganizingProjects.html#DevGuideModuleXml 

> One caveat specific to overriding JRE classes in this way is that they will never actually be used in development mode. In development mode, the native JRE classes always supercede classes compiled from source.

So, is it possible that my own module is working in super dev mode because it happens to be emulating a JRE class and is "getting assistance" from this behavior?

Both modules work fine outside of super dev mode as well. This behavior with guava-gwt only occurs in super dev mode. If so, I'll file a bug with GWT.

**Comment by tbroyer** [comment]
> The one thing that causes me concern is this note I read

This is actually only about the legacy dev mode, not super dev mode.
