### ISSUE TITLE
gwt:codeserver - jetty version

### ISSUE THREAD

**Issue by holgerhaag** [tbroyer/gwt-maven-plugin#112]
Hi,

we're tryting to harmonize jetty versions used in our different environments, with the final goal being to use latest jetty version (9.4.10). 

For "mvn jetty:run" the case is simple since it's just a value to be changed in the pom.xml for plugin org.eclipse.jetty.jetty-maven-plugin:

```
<plugin>
	<groupId>org.eclipse.jetty</groupId>
	<artifactId>jetty-maven-plugin</artifactId>
	<version> 9.4.10.v20180503</version>
</plugin>
```

mvn gwt:codeserver, however, will not pick up this value and start jetty version 9.2.14:

[INFO]    Module setup completed in 3905 ms
[WARNING] 2018-05-28 11:27:17.635:INFO:oejs.Server:main: jetty-9.2.14.v20151106

Is there a way to start another version of jetty for codeserver plugin? Or is that version determined outside the maven plugin?

**Comment by tbroyer** [comment]
> Is there a way to start another version of jetty for codeserver plugin? Or is that version determined outside the maven plugin?

Jetty is a dependency of `com.google.gwt:gwt-dev` (so it can technically be changed in your POM by adding a dependency or using dependencyManagement). Its version cannot be changed though without risking breakages (Jetty is infamous for introducing breaking changes even in point releases).
Jetty is an "implementation detail" of the CodeServer, it will not serve any of your code; you don't have any reason to change it.

**Comment by holgerhaag** [comment]
ok, thanks. That makes sense; gwt could have renamed it to"gwt-codeserver version 9.2.14 and I wouldn't have noticed..
