### ISSUE TITLE
Can gwt-maven-plugin specify the source folder to compile(or exclude some source to compile)

### ISSUE THREAD

**Issue by iamfuzi** [tbroyer/gwt-maven-plugin#114]
Hi, I am trying to use gwt-maven-plugin to refactor our old ant+ivy gwt project to a maven project.
But I met a problem that the gwt plugin compile server side code is different with javac compiler. I am wondering if the gwt maven plugin could specify the source folder for compiling or could I excude some source folder to compile? Thanks.

**Comment by tbroyer** [comment]
First, I must say I don't understand your problem (“the gwt plugin compile server side code is different with javac compiler”)

The plugin is designed towards projects where client and server code live in different Maven modules (generally within a single multi-module project), and shared code if any generally goes inside a third Maven module depended on by the other two; so there shouldn't be a need to ever exclude some Java sources (also, GWT reads files from its classpath –mostly–, and you cannot simply exclude files from the classpath).
However, that doesn't mean a setup where everything is in the same Maven module is impossible, it's just harder. If you have code that only runs on the server and lives in the same Java packages as code that runs on the client, then you can use [GWT's own include/exclude mechanisms to exclude the files](http://www.gwtproject.org/doc/latest/DevGuideOrganizingProjects.html#DevGuidePathFiltering). You can also annotate server code with [`@GwtIncompatible`](http://www.gwtproject.org/javadoc/latest/com/google/gwt/core/shared/GwtIncompatible.html).

But if you can, you should really split your project into separate Maven modules.

**Comment by iamfuzi** [comment]
Thanks for your reply.
Let me talk more detail about my project.
I have found this sample in git https://github.com/gwtproject/gwt/tree/master/samples/dynatablerf, which contains client, server and shared code in one project. So I try to follow this structure to refactor my project.
Everything goes well, but after package it as a war, it could not be launched in tomcat. I checked tomcat log file and found that there are some unresolved type in startup listener. So I use a decompile tool to see the startup listener class. And found that the import section has a problems: some imports only have the class name, they do not have the full package name. Eg: Import Injector;. That is why the exception occurs: unresolved type. The correct import should be: import com.google.inject.Injector;
At this time, I think maybe something wrong with compile. So I did a mvn compile for the project. And then check the startup listener class. The import section is correct. All classes have the right package name. After this, I run mvn clean package, after successfully executed, I checked the startup listener class again. This time, the import section occurs that problem: some imports only have class name without full package name. 
When I issue this cmd: mvn compile, it use javac as complier. When I issue mvn clean package, gwt:compiler is execute in prepare package phase. But the classes are different. So I guess that maybe gwt plugin do some thing different with the java code. So I am wondering whether I could exclude the server side code out of gwt plugin compile scope.
Currently, I have a workaround to solve this. I create 2 pom files. 1 pom package the project as jar. So I got javac compiled classes. The other pom package the project as war with gwt maven plugin. During package as war, I copied the jar files generated by the 1st pom to web-inf/lib and ignore the classes folder in web-in. But I think this is just a workaround, maybe I have some misunderstanding of the gwt maven plugin.
Not sure whether I describe the problem clearly.  Thanks for your time.

**Comment by tbroyer** [comment]
GWT shouldn't write any `*.class` file (even less so modifying existing ones); in most cases it actually doesn't even _read_ them. There must be something else going on… First, maybe try `mvn process-classes` rather than `mvn compile`. Then, you could run `mvn -X prepare-package` and get the command line used to actually run the GWT compiler from the debug output; then run `mvn clean process-classes` and manually run the GWT Compiler using that command.

But I really strongly suggest you split client and server code into distinct Maven modules (they don't have the same dependencies, don't need to be processed the same way, etc.) You can use https://github.com/tbroyer/gwt-maven-archetypes as a starting point or inspiration.

**Comment by iamfuzi** [comment]
Ok, I am trying to separate them to individual modules. But I got a problem, not sure whether it is ok.
The project has several GWT modules, only 1 module has entry point class and other GWT modules do not have an entry point. Let's call the module has entry point as ModuleA, It inherts other GWT modules. Could I put all the GWT modules in the gwt maven client module? Could gwt maven plugin compile these GWT modules correctly?
I am trying to split them to single GWT modules, but I found the code has circular dependencies. It is very difficult to split them. So I think put these GWT modules to a maven client module is the best solution. How do you think? Thanks.

**Comment by tbroyer** [comment]
It's totally OK putting more than one GWT module in the same Maven module, yes.

**Comment by iamfuzi** [comment]
hi, I have encountered some problem when I run this command in project root dir: mvn clean package.
`[INFO] Reactor Summary:
[INFO]
[INFO] gmx_main ........................................... SUCCESS [  0.089 s]
[INFO] gmx_main-shared .................................... SUCCESS [  1.614 s]
[INFO] gmx_main-client .................................... FAILURE [ 21.794 s]
[INFO] gmx_main-server .................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.260 s
[INFO] Finished at: 2018-07-10T17:31:01
[INFO] Final Memory: 39M/651M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-9:compile (default-compile) on project gmx_main-client: GWT exited with status 1 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-9:compile (default-compile) on project gmx_main-client: GWT exited with status 1
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: GWT exited with status 1
        at net.ltgt.gwt.maven.CommandLine.execute(CommandLine.java:50)
        at net.ltgt.gwt.maven.CompileMojo.execute(CompileMojo.java:202)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more
`

Let me clarify the structure of the project.
gmx_main-client contains client side code, it contains 3 GWT modules:MA, MB, MC. Java code are placed in java folder, GWT module defination files are placed in /src/main. MA has entry point, but MB, MC does not have an entry point. MA inherts from MB and MC, this has been declared in MA.gwt.xml.
gmx_main-server contains the server side code.
gmx_main-shared contians some shared code. This has been declared in MA.gwt.xml: <source path='shared'/>
├─gmx_main-client 
│  ├─.settings
│  ├─src
│  │  ├─main
│  │  │  ├─java
│  │  │  ├─resources
│  │  │  └─webapp
│  │  └─test
│  ├─target
│  └─pom.xml
├─gmx_main-server
│  ├─.settings
│  ├─src
│  │  ├─main
│  │  │  ├─java
│  │  │  ├─resources
│  │  │  └─webapp
│  │  └─test
│  ├─target
│  └─pom.xml
├─gmx_main-shared
│  ├─.settings
│  ├─src
│  │  ├─main
│  │  │  ├─java
│  │  │  └─resources
│  │  └─test
│  ├─target
│  └─pom.xml
├─pom.xml

in gmx_main-client pom file, I have configured these 3 GWT modules as below:
`	<build>
		<plugins>
			<plugin>
				<groupId>net.ltgt.gwt.maven</groupId>
				<artifactId>gwt-maven-plugin</artifactId>
				<executions>
					<execution>
						<id>compile-user</id>
						<goals>
							<goal>compile</goal>
						</goals>
						<configuration>
							<moduleName>com.xxx.xxx.gwt.user</moduleName>
							<moduleShortName>User</moduleShortName>
						</configuration>
					</execution>
					<execution>
						<id>compile-appswitcher</id>
						<goals>
							<goal>compile</goal>
						</goals>
						<configuration>
							<moduleName>com.xxx.xxx.xxx.xxx.AppSwitcher</moduleName>
							<moduleShortName>AppSwitcher</moduleShortName>
						</configuration>
					</execution>
					<execution>
						<id>compile-gmx</id>
						<goals>
							<goal>compile</goal>
						</goals>
						<configuration>
							<moduleName>com.xxx.xxx.xxx.GMX</moduleName>
							<moduleShortName>GMX</moduleShortName>
						</configuration>
					</execution>
				</executions>
				<configuration>
					<moduleName>com.xxx.xxx.xxx.GMX</moduleName>
					<moduleShortName>GMX</moduleShortName>
				</configuration>
			</plugin>
		</plugins>
	</build>`

Thanks for your time.

**Comment by tbroyer** [comment]
If I understood correctly, you only have one "application module" (MA), the other ones are "library modules"; so you only need to compile once, the application module. That module would be defined in `src/main/module.gwt.xml`, "library modules" would live in `src/main/resources` in their respective packages (alternatively, you could put all modules in `src/main/resources`, but then don't forget to skip the `generate-module` goal using `<skipModule>true</skipModule>`. That might be your problem here: `generate-module` will generate an almost-empty module (without entry point) overwriting the one you have in `src/main/resources`, which would lead to this error.

I'd suggest moving this to https://groups.google.com/forum/#!forum/google-web-toolkit (or StackOverflow) at this point.

**Comment by iamfuzi** [comment]
Thanks for your reply. The client module could be built successfully. 
I still have some questions: 
1. If I have defined some POJO class in the client module. But server module has dependencies with these classes. How to declare the dependency in server pom file. Currently, I just declare the client module in server pom file, but it has error: Failure to find com.xxx.xxx.xxx-client:jar. Because client module's package type is gwt-app, so the error is reasonable. I am not sure how to handle this case...
2. If I run mvn clean package in project root module, will it package all the classes and the generated js files into a war file?

**Comment by tbroyer** [comment]
> If I have defined some POJO class in the client module. But server module has dependencies with these classes.

This is what the _shared_ module is for (code that is shared between server and client).

> If I run mvn clean package in project root module, how it packages all the classes and the generated js files in the 3 maven modules into a war file?

If you started from one of my gwt-maven-archetypes, then yes, the _server_ module's WAR will contain the generated JS files and you should be able to drop it into any servlet container and run your app from there.

**Comment by iamfuzi** [comment]
Yes!! It makes sense. The POJO classes should be put in shared module.
I still have one question for the shared module and gwt module configuration file.
Refer to http://www.gwtproject.org/doc/latest/DevGuideOrganizingProjects.html#DevGuideModules
"_The default source path is the client subpackage underneath where the Module XML File is stored._"
In the GWT module configuration file, there is a tag <source> to specify the code will be translated. In the legacy project, the source tag contains 'client' and 'shared' folder like this:
`<source path='client'/>`
`<source path='shared'/>`
After split the project to 3 maven modules, there is a module called xxxx-shared, and I did not change the gwt configuration file in client module, I am not sure how GWT module(this is defined in the client maven module) find the shared source. I guess the client and shared modules have the same package structure, so the GWT module could still find where the shared code is located. How do you think?

**Comment by iamfuzi** [comment]
oh~ Thanks.
I want to clarify something to make sure I have no misunderstanding of the gwt maven plugin.
1. Client module use gwt-app as package type. In shared module, what package type should be? jar or gwt-lib? 
2. Does gwt-lib is only used for GWT module? or gwt-lib represents a lib module(this could be a gwt module or a comment java project has no relationship with GWT) that the client module depend on?
3. When I run mvn clean package at root level. It will execute all the build process of the modules defined in the root pom. Each module will generate the target in each module folder. For example, client module will generate a war file of the generated javascript related code. Shared module will generate a jar file. Server module is packaged as a war file. But I noticed that the war file does not include the client module code(gwt related things). So I have to specify what to be included in the war file. Does the plugin support automatic package client module code to the war file? What is the best practice?

**Comment by tbroyer** [comment]
> Client module use gwt-app as package type. In shared module, what package type should be? jar or gwt-lib?

See https://tbroyer.github.io/gwt-maven-plugin/
“With Maven, shared code is just a standard project with `jar` packaging.”

> Does gwt-lib is only used for GWT module? or gwt-lib represents a lib module(this could be a gwt module or a comment java project has no relationship with GWT) that the client module depend on?

See https://tbroyer.github.io/gwt-maven-plugin/artifact-handlers.html
“A `gwt-lib` is a JAR that contains both compiles classes and their sources.”

> When I run mvn clean package at root level. It will execute all the build process of the modules defined in the root pom. Each module will generate the target in each module folder. For example, client module will generate a war file of the generated javascript related code. Shared module will generate a jar file. Server module is packaged as a war file. But I noticed that the war file does not include the client module code(gwt related things). So I have to specify what to be included in the war file. Does the plugin support automatic package client module code to the war file? What is the best practice?

The server module should have a dependency on the client module with `<type>war</type>`, the `maven-war-plugin` should do the rest automatically; again, see https://tbroyer.github.io/gwt-maven-plugin/artifact-handlers.html; see also https://maven.apache.org/plugins/maven-war-plugin/overlays.html

**Comment by iamfuzi** [comment]
> A gwt-lib is a JAR that contains both compiles classes and their sources.
Oh~~I see. This means I could use gwt-lib as package type for GWT library modules, right?
The document is really good. Every time reading has new gains.

**Comment by iamfuzi** [comment]
I got this in the document. I think the anwser is yes.

> First, the applications and all modules from the reactor that are depended on with `<type>gwt-lib</type>` or `<classifier>sources</classifier>` have their source roots used as-is so that changes can be seen immediately;

**Comment by tbroyer** [comment]
Be careful, there are two `gwt-lib` actually: the `<type>` that you use in a dependency (aka _`gwt-lib` artifact handler_) and the `<packaging>` that you use in a project/module (aka _`gwt-lib` lifecycle_). Generally speaking, when you have a project using the `gwt-lib` lifecycle (`<packaging>`), you'll depend on it using `<type>gwt-lib</type>`.

The sentence you quoted only applies to dev mode though, where the JARs haven't been packaged so workarounds had to be found to still get the sources in the classpath (and have the most up-to-date ones, reacting to changes, etc.)

**Comment by tbroyer** [comment]
You need to set [`classpathScope`](https://tbroyer.github.io/gwt-maven-plugin/codeserver-mojo.html#classpathScope) to `runtime+system` then.

**Comment by tbroyer** [comment]
> `[WARNING] Error: Could not find or load main class com.google.gwt.dev.codeserver.CodeServer`

Double-check the scope of your `gwt-dev` dependency in your client module, specifically that it's not declared with `<scope>provided</scope>`. See https://tbroyer.github.io/gwt-maven-plugin/codeserver.html about classpath scope differences between `gwt:compile` and `gwt:codeserver`.
You should see the `gwt-dev` JAR in the classpath in the debug logs.

> Do I have to declare the type of these dependencies to gwt-lib?

If it is a GWT lib, you can declare it with `<type>gwt-lib</type>` to silence this message (or simply ignore it; that's why it's only emitted at debug level here); and if it's not then double-check why you have it in your client dependencies.
In this case `gwt-crypto` and `gwt-jackson` are gwt libs so those logs are OK, but hibernate-validator shouldn't be here (if you use bean validation on client-side –please not that it's deprecated, unmaintained for too long– then that must be version 4.1.0.Final, not 4.3.2.Final)

**Comment by iamfuzi** [comment]
Hi tbroyer, thanks for your help.
Now I could build the project as a war successfully. But I noticed that there is a bin folder under project root folder, it is the peer directory as XX-client, XX-server, XX-shared. In the bin folder, it has the three modules source code and target folder, and it very large. Not sure how this folder is generated. I did not see the configure in any pom file.

**Comment by tbroyer** [comment]
No idea, but not from the gwt-maven-plugin :man_shrugging:

**Comment by iamfuzi** [comment]
Thanks for your help. Now I could build and launch the project successfully. Without your help, I could not make it, thanks again.
