### ISSUE TITLE
New release for Java 10 support

### ISSUE THREAD

**Issue by TDesjardins** [tbroyer/gwt-maven-plugin#117]
The gwt-maven-plugin 1.0-rc-9 works on Java 10 when skipping tests. Seems that https://github.com/tbroyer/gwt-maven-plugin/commit/f10abc1f1f7b65d9a88c04058bf124a9ee2d9f0e is the only blocker to also support tests on Java 10. What about publishing a new release for Java 10 support?

**Comment by tbroyer** [comment]
1.0-rc-10 has just been released, and should hit Central soon.
