### ISSUE TITLE
Obfuscated method names in call stack

### ISSUE THREAD

**Issue by ak80** [tbroyer/gwt-maven-plugin#118]
This is not  an issue with the code but a problem on my side. I hope it is ok to put it here anyway...

I seem to be unable to configure the gwt style property correctly. Is it possible to get the method names in a not obfuscated way? 

For example when I look at the call stack in the Chrome DevTools, they are short and obfuscated. For the dev mode we would like to see the method names in clear text. 

We have a multi module project based on the multi module archtype. In the client module I have configured

```
                        <configuration>
                             <failOnError>true</failOnError>
                            <draftCompile>true</draftCompile>
                            <optimize>0</optimize>
                            <style>PRETTY</style>
                        </configuration>
```

Is the client module the right place to do this?

**Comment by tbroyer** [comment]
Configuration for the `devmode` and `codeserver` goals should go in the root module (next to the `<launcherDir>`), because that's where they're actually executed.

There's no `<style>` on these goals though (I should probably add it, it's been added in GWT proper more than 3 years ago now), so you'll have to use:
```xml
<codeserverArgs>
  <arg>-style</arg><arg>PRETTY</arg>
</codeserverArgs>
```

**Comment by ak80** [comment]
Great, that works as we need it. Thank you very much.

**Comment by tbroyer** [comment]
Fwiw, just added `<style>` (also `-Dgwt.style=` on the command line) to `codeserver` and `devmode` in eb9ef1b3209700b6d8dffbc65d97c1ef11bc7e17; will be in the next release.

**Comment by ak80** [comment]
Thank you, I have added reminder for us so we can migrate with the next release
