### ISSUE TITLE
IntelliJ plugin

### ISSUE THREAD

**Issue by gitgabrio** [tbroyer/gwt-maven-plugin#121]
Hi,
sorry if I'm posting in the wrong place.
I've just done a first prototype of an IntelliJ "Run configuration" plugin  that just launches the codeserver and the jetty on different terminals. As it is, it is just a shortcut to avoid issuing the two commands on the terminal. Do you think it could be useful to have it, eventually with more features?

**Comment by tbroyer** [comment]
Unless things are to be done in the Maven plugin itself for IDE integration (like `META-INF/m2e/lifecycle-mapping-metadata.xml` for Eclipse), this is the “wrong place”.

I could however possibly add a link to an IntelliJ IDEA plugin from the README. If you publish something, I'd encourage advertising it on https://groups.google.com/forum/#!forum/google-web-toolkit too.

Fwiw, a quick search lead to https://plugins.jetbrains.com/plugin/7248-multirun; I don't know how close to your plugin this approach is.

**Comment by gitgabrio** [comment]
Hi Thomas,
thanks for your answer! Multirun seems a little bit "generic", while I wanted to do something more specific for your maven plugin. I agree it is a bit "curious" to have an IDE-plugin to launch a maven one, so if I can not give it some real use, I'll stop to work on it.
Anyway, thanks for your job on the GWT plugin!
Gabriele
