### ISSUE TITLE
Usage in simple gwt app

### ISSUE THREAD

**Issue by mdathersajjad** [tbroyer/gwt-maven-plugin#123]
All example archtypes are multi modular applications. Is there a way to integrate in a single module applications. We are trying to convert our GWT app to Java 10. I got info from google group like this plugin supports Java10. We are not looking for java 10 features we just want to run GWT in Java10 runtime.

It will be really helpful if you point out how to migrate from mojo plugin to this plugin. 

Regards
Sajjad

**Comment by tbroyer** [comment]
> All example archtypes are multi modular applications. Is there a way to integrate in a single module applications.

Yes, but I don't recommend it. See https://blog.ltgt.net/announcing-gwt-maven-archetypes-project/ and, for example, the very last line of https://tbroyer.github.io/gwt-maven-plugin/codeserver.html
(and note that the archetypes predate the creation of this plugin)
That said, you can actually find an example in GWT's own samples: https://github.com/gwtproject/gwt/tree/2.8.2/samples/dynatablerf

> We are trying to convert our GWT app to Java 10. I got info from google group like this plugin supports Java10. We are not looking for java 10 features we just want to run GWT in Java10 runtime.

Fwiw, the only issue I had in this plugin was Surefire (i.e. `gwt:test`), which the MojoHaus plugin doesn't directly use AFAIK. Have you actually confirmed your project cannot use JDK 10 with the MojoHaus plugin?

> It will be really helpful if you point out how to migrate from mojo plugin to this plugin.

Have you tried https://tbroyer.github.io/gwt-maven-plugin/migrating.html ?

**Comment by mdathersajjad** [comment]
Previous plugin doesn't work with Java10. I can't convince my manager to move to multimodular. I tried creating a new project in eclipse with maven. It generates a sample project with your plugin only . But i am facing this issue when running

java.lang.NoClassDefFoundError: javax/servlet/Servlet

Can you please point out what went wrong here

Thanks

**Comment by tbroyer** [comment]
Assuming your POM then looks like https://github.com/gwtproject/gwt/blob/2.8.2/user/src/com/google/gwt/user/tools/templates/maven/pom.xmlsrc, what do you mean by "when running"? `mvn package`? `mvn gwt:devmode`? or through the GWT Eclipse Plugin?

**Comment by mdathersajjad** [comment]
Thanks for responding. The generated eclipse project has the same pom as it given here
https://github.com/gwtproject/gwt/blob/2.8.2/user/src/com/google/gwt/user/tools/templates/maven/pom.xmlsrc. I tired mvn package it builds successfully. When i run mvn gwt:devmode or From GWT Eclipse Plugin(Run As -> GWT Development mode with jetty) i am getting this error. 

`[WARNING] java.lang.NoClassDefFoundError: javax/servlet/Servlet
[WARNING] 	at com.google.gwt.dev.codeserver.SourceHandler.<clinit>(SourceHandler.java:63)
[WARNING] 	at com.google.gwt.dev.codeserver.Recompiler.loadModule(Recompiler.java:500)
[WARNING] 	at com.google.gwt.dev.codeserver.Recompiler.initWithoutPrecompile(Recompiler.java:204)
[WARNING] 	at com.google.gwt.dev.codeserver.Outbox.maybePrecompile(Outbox.java:89)
[WARNING] 	at com.google.gwt.dev.codeserver.Outbox.<init>(Outbox.java:61)
[WARNING] 	at com.google.gwt.dev.codeserver.CodeServer.makeOutboxTable(CodeServer.java:192)
[WARNING] 	at com.google.gwt.dev.codeserver.CodeServer.start(CodeServer.java:151)
[WARNING] 	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:104)
[WARNING] 	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:55)
[WARNING] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[WARNING] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[WARNING] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[WARNING] 	at java.lang.reflect.Method.invoke(Method.java:497)
[WARNING] 	at com.google.gwt.dev.shell.SuperDevListener.runCodeServer(SuperDevListener.java:112)
[WARNING] 	at com.google.gwt.dev.shell.SuperDevListener.start(SuperDevListener.java:91)
[WARNING] 	at com.google.gwt.dev.DevMode.ensureCodeServerListener(DevMode.java:666)
[WARNING] 	at com.google.gwt.dev.DevModeBase.doStartup(DevModeBase.java:810)
[WARNING] 	at com.google.gwt.dev.DevMode.doStartup(DevMode.java:551)
[WARNING] 	at com.google.gwt.dev.DevModeBase.startUp(DevModeBase.java:913)
[WARNING] 	at com.google.gwt.dev.DevModeBase.run(DevModeBase.java:706)
[WARNING] 	at com.google.gwt.dev.DevMode.main(DevMode.java:432)
[WARNING] Caused by: java.lang.ClassNotFoundException: javax.servlet.Servlet
[WARNING] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[WARNING] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[WARNING] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[WARNING] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[WARNING] 	... 21 more`

**Comment by tbroyer** [comment]
Are you sure you have `<classpathScope>compile+runtime</classpathScope>`?

Does `mvn dependency:tree` show a `javax.servlet` dependency?

If you run `mvn -X gwt:devmode` (I'd suggest redirecting the output to a file as it's going to be really verbose), do you find that `javax.servlet` dependency on the `[DEBUG] Classpath:` line?

Last, but not least, did you make sure you're using the last version of the plugin?

**Comment by mdathersajjad** [comment]
Are you sure you have <classpathScope>compile+runtime</classpathScope>? 
Yes its there

Does mvn dependency:tree show a javax.servlet dependency?
Yes it is showing as below.
[INFO] |  +- javax.servlet:javax.servlet-api:jar:3.1.0:provided
[DEBUG]       javax.servlet:javax.servlet-api:jar:3.1.0:provided

Do you find that javax.servlet dependency on the [DEBUG] Classpath: line?
Yes it is displaying the dependancy as below
 /Users/balabhaskar/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar

Did you make sure you're using the last version of the plugin?
Yes i am using the latest version of plugin 3.0.0

**Comment by tbroyer** [comment]
> > Do you find that javax.servlet dependency on the [DEBUG] Classpath: line?
> Yes it is displaying the dependancy as below
> /Users/balabhaskar/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar

If it's on the classpath and you have a `java.lang.NoClassDefFoundError: javax/servlet/Servlet`, then check that it's not corrupt, because that class should be in that JAR.

> > Did you make sure you're using the last version of the plugin?
> Yes i am using the latest version of plugin 3.0.0

I was talking about the `gwt-maven-plugin` here, not the GWT Eclipse Plugin :wink:

**Comment by mdathersajjad** [comment]
Thank you brother after updating the corrupted jar and updating the maven plugin to version rc8. It worked sorry for the trouble. Going to test it in Java10.

Is the version 1.0-rc-8 stable to use for production.

Cheers 
😉

**Comment by tbroyer** [comment]
> Is the version 1.0-rc-8 stable to use for production.

It is.

But you should use 1.0-rc-10: https://github.com/tbroyer/gwt-maven-plugin/releases

**Comment by tbroyer** [comment]
`<jvmArgs>` is a list (https://tbroyer.github.io/gwt-maven-plugin/compile-mojo.html#jvmArgs), so:
```xml
<jvmArgs>
  <arg>-Xms1024M</arg>
  <arg>-Xmx1024M</arg>
</jvmArgs>
```

**Comment by tbroyer** [comment]
Run Maven with debug logs (`mvn -X`) to see what exact arguments are passed to the forked JVM. If the plugin correctly passes `Xms1024M -Xmx1024M`, then there's no issue with the plugin, you could then ask for help in [the GWT forum](https://groups.google.com/forum/#!forum/google-web-toolkit)
