### ISSUE TITLE
SuperDevMode - Not recompiling JS in public directory

### ISSUE THREAD

**Issue by phuongtailtranminh** [tbroyer/gwt-maven-plugin#124]
Hi,

I'm working on the Che plugin project which is using gwt-maven-plugin and its Super Dev Mode (SDM) feature.

The JS is placed under REVERSE.PACKAGE.NAME.public directory

When the content of JS file is changed, seem like SDM doesn't pick it up

I believe that there is a solution for this without externally load the JS into my app

**Comment by tbroyer** [comment]
This plugin is only responsible for launching GWT's SDM, and the copying of public resources is done by SDM itself; so I'll close this issue.

FYI, SDM will copy the public resources at startup and then each time it recompiles the module (but not when the only change is in the public resources). A workaround would then be to _touch_ any Java file to trigger a recompilation.

I'd suggest you post to the [GWT forum](https://groups.google.com/forum/#!forum/google-web-toolkit) if you have issues making it work.
