### ISSUE TITLE
How to Create a Deployable War File

### ISSUE THREAD

**Issue by randymay-insclix** [tbroyer/gwt-maven-plugin#133]
I have refactored my multi-module Maven project to use the gwt-maven-plugin, and the resulting War is able to be successfully run with GWT's Super Dev Mode.  This project has a few pure Server-side Jar files, and a few Client-side Jar files (using the <packaging>gwt-lib</packaging> tag), and one module which creates the deployable War file (using the <packaging>gwt-app</packaging> tag).  The client-side source modules were supplied to the war project using the old gwt-maven-plugin using the <compileSourcesArtifacts> tags. 
What I am struggling with now is how to create a War file which can be deployed on it's own (the same way it was before).  Now, the War file that is produced does not have the web.xml or Java classes.  I understand this is by design, but I am wondering what the desired approach is to properly create a deployable War file?

**Comment by tbroyer** [comment]
See https://tbroyer.github.io/gwt-maven-plugin/artifact-handlers.html#GWT_Application:_gwt-app and https://tbroyer.github.io/gwt-maven-plugin/#Archetypes

Split your client, shared and server code into separate Maven modules; "import" the `gwt-app` as a war overlay in a standard `war` module.

**Comment by randymay-insclix** [comment]
Using the overlay, I'm still not able to get the compiled GWT artifacts out of the gwt-app, as they are not part of the resulting war file.  
Is there a way to get the compiled GWT artifacts without having to recompile?
