### ISSUE TITLE
Extract GWT compiled artifacts

### ISSUE THREAD

**Issue by randymay-insclix** [tbroyer/gwt-maven-plugin#134]
In a multi module project with the following modules:

gwt-lib-1
gwt-lib-2
gwt-app-1
war-1

What is the right way to get the the GWT compiled artifacts that are in the gwt-app-1, and place them in the resulting war for war-1?  I can see that the artifacts are being created in gwt-app-1, and war-1 has an overlay to access gwt-app-1, but the GWT artifacts are not contained in the resulting war (for gwt-app-1), so the overlay doesn't seem to have the ability to access them.
I don't think I should have to recreate them in war-1. 
Do I have to use a <resource> tag with a relative path?

**Comment by tbroyer** [comment]
As I explained in #133, this works in the gwt-maven-archetypes, so it must be either a configuration issue or coming from your invocation of Maven (assuming gwt-app-1 has `<packaging>gwt-app</packaging>`)

Can you share your war-1 POM? Also how are you invoking Maven (which goals)?
