### ISSUE TITLE
 Source file is newer than nocache.js, recompiling: pathToModule\.flattened-pom.xml

### ISSUE THREAD

**Issue by alpapad** [tbroyer/gwt-maven-plugin#135]
When flatten-maven-plugin is used for the build, then the module is always recompiled.

Seems flatten-maven-plugin generates a .flattened-pom.xml for every build and this is used for compiling. The .flattened-pom.xml  is always newer than  nocache.js and as a result the module gets recompiled even if there are no changes.

Sample  flatten-maven-plugin config

	<groupId>aaaa</groupId>
	<artifactId>bbbb</artifactId>
	<version>${revision}</version>

	<properties>
		<revision>1.2.3</revision>
         </properties>

	<build>
		<pluginManagement>
			<plugins>
		<plugin>
		      <groupId>org.codehaus.mojo</groupId>
		      <artifactId>flatten-maven-plugin</artifactId>
		      <version>1.1.0</version>
		      <configuration>
		        <updatePomFile>true</updatePomFile>
		        <flattenMode>resolveCiFriendliesOnly</flattenMode>
		      </configuration>
		      <executions>
		        <execution>
		          <id>flatten</id>
		          <phase>process-resources</phase>
		          <goals>
		            <goal>flatten</goal>
		          </goals>
		        </execution>
		        <execution>
		          <id>flatten.clean</id>
		          <phase>clean</phase>
		          <goals>
		            <goal>clean</goal>
		          </goals>
		        </execution>
		      </executions>
		    </plugin>	
....

**Comment by tbroyer** [comment]
flatten-maven-plugin 1.2.0 should no longer unnecessarily overwrite the `.flattened-pom.xml`: https://github.com/mojohaus/flatten-maven-plugin/issues/96

Alternatively, you could run the `flatten` goal at a later time (`package` phase?), such that `gwt:compile` doesn't see it (but the original `pom.xml`)
