### ISSUE TITLE
Compile gwt-app to jar instead of war?

### ISSUE THREAD

**Issue by sjardine** [tbroyer/gwt-maven-plugin#140]
It is possible for gwt-maven-plugin to compile the gwt-app packaging to a jar instead of a war?

Our current project uses the previous plugin to compile into a jar file to be included in a parent jar or war.

**Comment by tbroyer** [comment]
It's not possible. Would the idea be to

You can achieve it by using another packaging (e.g. `jar`) and reproducing the `gwt-app` lifecycle (https://tbroyer.github.io/gwt-maven-plugin/lifecycles.html) with the exception of the `gwt:package-app`.

This plugin can actually also be used the same way as Mojo's Maven plugin for GWT, only running the `gwt:compile` mojo (you'll have to configure the `<projects>` of the `gwt:codeserver` (or `gwt:devmode`) mojo(s) though, as auto-discovery is based on the `gwt-app` packaging)
