### ISSUE TITLE
Version 1.0.0 do not support GWT 2.1.0

### ISSUE THREAD

**Issue by yisiliang** [tbroyer/gwt-maven-plugin#141]
Env:
* maven version: 3.6.0
* gwt-maven-plugin version: 1.0.0
* gwt version: 2.1.0
* java version: 1.8.0_231

Maven output:
```
[INFO] --- gwt-maven-plugin:1.0.0:compile (default) @ widget ---
[WARNING] Unknown argument: -deploy
[WARNING] Google Web Toolkit 2.1.0
[WARNING] Compiler [-logLevel level] [-workDir dir] [-gen dir] [-style style] [-ea] [-XdisableClassMetadata] [-XdisableCastChecking] [-validateOnly] [-draftCompile] [-optimize level] [-compileReport] [-strict] [-localWorkers count] [-war dir] [-extra dir] module[s] 
[WARNING] 
[WARNING] where 
[WARNING]   -logLevel               The level of logging detail: ERROR, WARN, INFO, TRACE, DEBUG, SPAM, or ALL
[WARNING]   -workDir                The compiler's working directory for internal use (must be writeable; defaults to a system temp dir)
[WARNING]   -gen                    Debugging: causes normally-transient generated types to be saved in the specified directory
[WARNING]   -style                  Script output style: OBF[USCATED], PRETTY, or DETAILED (defaults to OBF)
[WARNING]   -ea                     Debugging: causes the compiled output to check assert statements
[WARNING]   -XdisableClassMetadata  EXPERIMENTAL: Disables some java.lang.Class methods (e.g. getName())
[WARNING]   -XdisableCastChecking   EXPERIMENTAL: Disables run-time checking of cast operations
[WARNING]   -validateOnly           Validate all source code, but do not compile
[WARNING]   -draftCompile           Enable faster, but less-optimized, compilations
[WARNING]   -optimize               Sets the optimization level used by the compiler.  0=none 9=maximum.
[WARNING]   -compileReport          Create a compile report that tells the Story of Your Compile
[WARNING]   -strict                 Only succeed if no input files have errors
[WARNING]   -localWorkers           The number of local workers to use when compiling permutations
[WARNING]   -war                    The directory into which deployable output files will be written (defaults to 'war')
[WARNING]   -extra                  The directory into which extra files, not intended for deployment, will be written
[WARNING] and 
[WARNING]   module[s]               Specifies the name(s) of the module(s) to compile
```

**Comment by yisiliang** [comment]
I have forked this project and removed below two lines, it works.
![1593346277831](https://user-images.githubusercontent.com/8147509/85947160-97f8c380-b97b-11ea-9412-8e652d0932ee.jpg)

**Comment by tbroyer** [comment]
2.1.0 will be **10 YEARS OLD** in a few months ([source](http://www.gwtproject.org/release-notes.html)), so yes indeed it's not supported!
(also, keep in mind that in GWT's front, only the latest version is "supported", which is 2.9.0 now)

**Comment by yisiliang** [comment]
> 2.1.0 will be **10 YEARS OLD** in a few months ([source](http://www.gwtproject.org/release-notes.html)), so yes indeed it's not supported!
> (also, keep in mind that on GWT's front, only the latest version is "supported", which is 2.9.0 now)

ok, thank you. I will fork this project and modify it...

**Comment by tbroyer** [comment]
If you don't want to or can't upgrade your GWT version, then yes either use your own fork of this plugin, or possibly use the [`org.codehaus.mojo:gwt-maven-plugin:2.1.0-1` plugin](https://search.maven.org/artifact/org.codehaus.mojo/gwt-maven-plugin/2.1.0-1/maven-plugin) from ~10 years ago.

**Comment by yisiliang** [comment]
> If you don't want to or can't upgrade your GWT version, then yes either use your own fork of this plugin, or possibly use the [`org.codehaus.mojo:gwt-maven-plugin:2.1.0-1` plugin](https://search.maven.org/artifact/org.codehaus.mojo/gwt-maven-plugin/2.1.0-1/maven-plugin) from ~10 years ago.

Only GWT 1.* and 2.1.* do not support the deploy parameter. 
But my App is built with Vaadin 6.5.0, so I can't upgrade to the newer GWT.
Thank you very much.
