### ISSUE TITLE
GWT 2.9.0

### ISSUE THREAD

**Issue by eliasbalasis** [tbroyer/gwt-maven-plugin#147]
I haven't tried this, but I wonder:

Is the Maven goal for DevMode working with GWT 2.9.0 , or is it suffering from the known GWT 2.9.x build classpath symptoms as the ones mentioned under (https://github.com/gwtproject/gwt/issues/9720) and the referenced issues

**Comment by tbroyer** [comment]
Don't use DevMode except for static files in standalone / client-only apps, it's as simple as that: https://tbroyer.github.io/gwt-maven-plugin/codeserver.html

But to answer your question, given that this plugin only runs GWT in forked JVMs, without any modification or even classpath/classloader tricks, then yes it suffers from the same limitations.
The advice above applies to GWT generally, whether run through this plugin or anything else (Ant, Gradle, your IDE, etc.)

**Comment by eliasbalasis** [comment]
Thanks for confirming.

I was referring to "Super DevMode" not standard "DevMode", which I am using via "Google Plugin for Eclipse" but I have to agree that even though "codeserver" is not as simple it at least bypasses the Jetty runtime classpath issues.
