### ISSUE TITLE
goal codeserver fails when web app dependencies are managed in a BOM pom

### ISSUE THREAD

**Issue by emweber** [tbroyer/gwt-maven-plugin#162]
In my project I manage the dependencies of the _gwt-app_ in a maven BOM.
When I run the codeserver goal I get info messages that my 

1. client-server-shared dependencies are ignored (I depend on the sources, too, so this may be a false info).
2. client-side dependencies (packages as _gwt-lib_) are ignored.

Additionally, the gwt compiler has errors saying that it coul not find source code living in the _gwt-lib_ module.
The messages are like `Ignoring groupId:artifactId:jar; neither a gwt-lib or jar:sources; Did you forget to use <type>gwt-lib</type> in the dependency declaration?`.
BTW: Looking at the code in `AbstractDevModeMojo.java`, I think the message is misleading. The code looks a the packaging type of the pom of the library I depend on. It does not look at the `type` tag of the pom where the dependency is declared.

If I add `<type>gwt-lib</type>` to the dependency in the **BOM** pom as the messages suggests, I get a maven error: `'dependencies.dependency.version' for groupId:client:jar is missing.`
If I add `<type>gwt-lib</type>` to the dependency in the **gwt-app** pom, I get a similar maven error: 
`'dependencies.dependency.version' for groupId:client:gwt-lib is missing.`
If I add both `<type>gwt-lib</type>` and `<version>1.0</version>` to the dependency in the **gwt-app** pom, I still get the _Did you forget to use..._ message but the gwt compiler finds all needed sources. But being forced to have to add these two tags to the dependencies makes BOM-managed dependencies effectively useless.

Both the client-server-shared project and the  _gwt-lib_ project live in the **same reactor**.

Further notice: For dependencies of type _gwt-lib_ or _jar:sources_ that get **resolved from the maven repo**, managing them in a BOM works as expected: No need to specify `<type>gwt-lib</type>` anywhere, no `neither a gwt-lib or jar:sources...` messages.

**Comment by tbroyer** [comment]
It's not entirely clear to me how your reactor is setup. Could you provide a small reproducer?

Wrt `<type>`, it needs to be added in both the dependency-management (the BOM) and the dependencies (the actual project), as it's part of the key used to lookup the version in the dependency-management (AFAICT, only the version and scope can be *managed*, the rest is part of the lookup key). But for reactor dependencies, they should be seen as project dependencies by Maven and handled differently by the plugin.

**Comment by emweber** [comment]
[Reproducer gwt-bom-test.zip](https://github.com/tbroyer/gwt-maven-plugin/files/12418328/gwt-bom-test.zip)
You might notice that it does not specify `<type>gwt-lib</type>` in any of the dependency declarations.
I also cloned this repo and did some investigation.
If I modifiy `AbstractDevModeMojo.java` (line 304++) to also check the pom-packaging type for reactor projects before ignoring an artifact, the codeserver goal works without any `<type>gwt-lib</type>`.
Should I submit a PR?
