### ISSUE TITLE
converting from old plugin with compileSourcesArtifacts

### ISSUE THREAD

**Issue by localdevjs** [tbroyer/gwt-maven-plugin#168]
I'm trying to migrate my project from old gwt maven plugin to this plugin.

Some of my gwt code relies on artifacts in my ".m2/repository", the sources are separated from the classes like this:
.m2/repository/.../util.jar
.m2/repository/.../util-sources.jar

I can't control that, that's a different build process outside my control.

Now in my gwt project's pom.xml, I used to use the codehaus.mojo plugin which had a "compileSourcesArtifacts" which enabed gwt to see the dependecy sources.

How do I include those dependency sources in my "net.ltgt.gwt.maven" plugin as there is no element for this?

**Comment by tbroyer** [comment]
You _just_ have to declare those dependencies explicitly, with `<classifier>sources</classifier>`, as touched upon in https://tbroyer.github.io/gwt-maven-plugin/

```xml
<dependency>
  <groupId>com.example</groupId>
  <artifactId>util</artifactId>
  <version>1.0.0</version>
</dependency>
<dependency>
  <groupId>com.example</groupId>
  <artifactId>util</artifactId>
  <version>1.0.0</version>
  <classifier>sources</classifier>
</dependency>
```

(you have to declare **all** of them, including for transitive dependencies)

**Comment by localdevjs** [comment]
That worked, thank you!
