### ISSUE TITLE
Remove gwt:generate-module doc tip from README.md

### ISSUE THREAD

**Issue by manolo** [tbroyer/gwt-maven-plugin#17]
It seems that gwt:generate-module option is not supported anymore but it is documented in the project welcome file.

**Comment by tbroyer** [comment]
Yes it's still there: https://github.com/tbroyer/gwt-maven-plugin/blob/00afe2770bf7d4e3bcc66846fa3455dca4a4fcb5/src/main/java/net/ltgt/gwt/maven/GenerateModuleMojo.java
…and used (and therefore tested) in the lifecycle: https://github.com/tbroyer/gwt-maven-plugin/blob/00afe2770bf7d4e3bcc66846fa3455dca4a4fcb5/src/main/resources/META-INF/plexus/components.xml#L23
