### ISSUE TITLE
[Question] Motivation behind required gwt-dev dependency

### ISSUE THREAD

**Issue by TanyaGaleyev** [tbroyer/gwt-maven-plugin#172]
Hi,

I am migrating a project to gwt-maven-plugin (from Mojo's) and using the opportunity to cleanup my pom. It turns out that org.gwtproject:gwt-dev module is neither needed to compile the code of my project, nor used in runtime. However, without it gwt-maven-plugin fails to execute as it cannot find class com.google.gwt.dev.Compiler. And gwt-dev requirement is clearly stated in the documentation [1].

I am not a big GWT expert, so my question could be silly. Is it technically possible to load gwt-dev classes not from the project's classpath, but from the plugin's or somehow else? Or am I totally getting in wrong and gwt-dev is always on classpath for every GWT project? (I wonder what for)

[1] https://tbroyer.github.io/gwt-maven-plugin/

**Comment by tbroyer** [comment]
This plugin is meant to be used in projects where server and client code is clearly separated in distinct modules, so adding gwt-dev as a dependency is not a problem at all.
In projects with client and server code mixed in the same module, you can add gwt-dev in some scope where it doesn't cause you harm (e.g. provided or test) and adjust the scopes used by the plugin.

But there's no way to load gwt-dev from elsewhere and I don't plan on adding this option.

**Comment by TanyaGaleyev** [comment]
@tbroyer thank you for the prompt response! Yes, with client/server modules separation it makes perfect sense.

> you can add gwt-dev in some scope where it doesn't cause you harm (e.g. provided or test) and adjust the scopes used by the plugin

Actually, I tried but didn't succeed with it. I see `classpathScope` parameter for `codeserver` and `devmode` goals, but not for `compile` goal.
