### ISSUE TITLE
[Question] How to get the plugin to use a specific bindAddress ?

### ISSUE THREAD

**Issue by ffrancois465** [tbroyer/gwt-maven-plugin#173]
Hi,

I am working with the gwt-maven-plugin using an embedded jetty server for my project. Migrating from another commonly used plugin I was able to set the bindAddress within the plugin configuration (using the `bindAddress` parameter). Now this parameter has disappeared and I am facing issues with the codeServer.
To be more precise about the context : I am developing using a Windows computer, but for ease of use I installed all my IDEs inside a WSL container, which prevents any Windows/Linux file systems incompatibility issues when sharing code with my colleagues. Since we migrated to this plugin, my Windows web browser cannot contact the code server and I cannot use the application this way. By changing the bind address to `0.0.0.0` with the previous plugin I was able to make it work.

Is there any way to specify the bind address in coderserver configuration so that not only `localhost` or `127.0.0.1` is usable ?

**Comment by tbroyer** [comment]
See the [Migrating from Mojo's Maven Plugin for GWT](https://tbroyer.github.io/gwt-maven-plugin/migrating.html) documentation:
> Finally, the way you configure the plugin is much different: the Maven Plugin for GWT has few properties, and arguments are passed to GWT explicitly through list properties (`<compilerArgs>` et al.)

All arguments to GWT tools can be passed through the appropriate properties:
* [`compilerArgs`](https://tbroyer.github.io/gwt-maven-plugin/compile-mojo.html#compilerArgs) for the [compiler arguments](https://www.gwtproject.org/doc/latest/DevGuideCompilingAndDebugging.html#DevGuideCompilerOptions),
* [`devmodeArgs`](https://tbroyer.github.io/gwt-maven-plugin/devmode-mojo.html#devmodeArgs) for the [DevMode arguments](https://www.gwtproject.org/doc/latest/DevGuideCompilingAndDebugging.html#What_options_can_be_passed_to_development_mode), and
* [`codeserverArgs`](https://tbroyer.github.io/gwt-maven-plugin/codeserver-mojo.html#codeserverArgs) for the [CodeServer arguments](https://www.gwtproject.org/articles/superdevmode.html#Starting)

So:
```xml
<plugin>
  <groupId>net.ltgt.gwt.maven</groupId>
  <artifactId>gwt-maven-plugin</artifactId>
  <configuration>
    <!-- … -->
    <devmodeArgs>
      <arg>-bindAddress</arg><arg>0.0.0.0</arg>
    </devmodeArgs>
  </configuration>
</plugin>
```

And if you want to be able to control it from the command line, use a Maven property and/or a profile (in which case [`combine.children="append"`](https://maven.apache.org/pom.html#advanced_configuration_inheritance) can prove useful)
