### ISSUE TITLE
Support java class files inside a jar?

### ISSUE THREAD

**Issue by happyhua** [tbroyer/gwt-maven-plugin#174]
By running Maven build I see this kind of message.

_[INFO] --- gwt:1.1.0:codeserver (default-cli) @ parent ---
[INFO] Ignoring xxx:shared:jar:1.0; neither a gwt-lib or jar:sources; Did you forget to use <type>gwt-lib</type> in the dependency declaration?_

Does it mean that I can not use a shared jar (with source java files included) dependency, I have to include sources classifier explicitly in a maven dependency?

        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>shared</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>shared</artifactId>
            <version>${project.version}</version>
            <classifier>sources</classifier>
        </dependency>

**Comment by tbroyer** [comment]
If sources (and gwt.xml) are included in the jar, then from the plugin's point of view it's a GWT library so you can use `<type>gwt-lib</type>`.

If it's a shared library though then I'd rather package the sources separately and use the two dependencies with and without `<classifier>sources</classifier>`. There's no point in deploying the sources to the server.
