### ISSUE TITLE
Pass compilerArgs via command line

### ISSUE THREAD

**Issue by timeu** [tbroyer/gwt-maven-plugin#20]
This is probably not a `gwt-maven-plugin` specific issue but a general maven issue.  Currently the gwt-maven-plugin only supports a handful GWT compiler args. The remaining must be passed via the parameter `compilerArgs`. 
This can be done in the `pom.xml` in the following way (i..e enable compileReport): 

```XML
<plugin>
    <groupId>net.ltgt.gwt.maven</groupId>
    <artifactId>gwt-maven-plugin</artifactId>
    <configuration>
         <moduleName>${gwt.module}</moduleName>
         <compilerArgs>
             <compileArg>-compileReport</compileArg>
         </compilerArgs>
     </configuration>
</plugin>
```

But when I try to pass it via command line it doesn't really work (http://books.sonatype.com/mvnref-book/reference/writing-plugins-sect-mojo-params.html): 

`mvn gwt:compile "-DcompilerArgs=-compileReport"`
or 
`mvn gwt:compile "-Dgwt.compilerArgs=-compileReport"`

**Comment by tbroyer** [comment]
[The `compilerArgs` parameter doesn't have a `property`](https://github.com/tbroyer/gwt-maven-plugin/blob/c21afbf401dde14997d04f5667f7aae7763a7d61/src/main/java/net/ltgt/gwt/maven/CompileMojo.java#L115-L119) to be set in the POM's `<properties>` or as a system property from the command line. This is on-purpose.

Currently, you can define "presets" using profiles, possibly appending new arguments using `combine.item="append"`: http://blog.sonatype.com/2011/01/maven-how-to-merging-plugin-configuration-in-complex-projects/

To make it work from the command-line, the plugin would have to parse the property value as a "command line" to split arguments apart (there's `CommandLineUtils#translateCommandline` from plexus-utils that can help), but that also means there needs to be another property that accepts a command-line as a `String`, and that raises the question of what to do when both that property **and** `<compilerArgs>` are non-empty.

The current design is based on the maven-compiler-plugin, which doesn't allow setting the compiler arguments from the command-line. I'm tempted to close this issue as a _wontfix_ but could possibly accept a pull-request if things are kept simple.

**Comment by timeu** [comment]
@tbroyer Thanks for the explanation. 
I guess the workaround using profiles ist just fine. Are there plans to expose GWT's compiler arguments as properties ? 
Maybe it would be worth to update the `README.MD` to include some documentation of how to add custom compiler arguments to the GWT compiler. I can do a pull-request if you like.

**Comment by tbroyer** [comment]
The plugin documentation is now published at https://tbroyer.github.io/gwt-maven-plugin/ and I linked to it form the README. I think that's enough, particularly:

 * https://tbroyer.github.io/gwt-maven-plugin/compile-mojo.html#compilerArgs
 * https://tbroyer.github.io/gwt-maven-plugin/migrating.html
