### ISSUE TITLE
Css -> java generation

### ISSUE THREAD

**Issue by biancashouse** [tbroyer/gwt-maven-plugin#26]
Firstly, I want to say it's a relief to know that there is some kind of future for the maven-gwt-plugin. The closing down of codehaus is a shock to me, and I suspect will frighten many devs around the world. So many thanks.

I think one of the most useful aspects of the codeaus mojo is that it generates all your java resource classes from the ,css files. To start doing this by hand is going to be a P.I.T.A.

Is there a plan to do CSS generation in your plugin ? or is there a new way that I'm obviously not aware of ?

Once again, thanks for the great work you and your pals do for the GWT community.

**Comment by tbroyer** [comment]
> Firstly, I want to say it's a relief to know that there is some kind of future for the maven-gwt-plugin. The closing down of codehaus is a shock to me, and I suspect will frighten many devs around the world. So many thanks.

CodeHaus may be closed, but Mojo is still alive and well: http://www.mojohaus.org / https://github.com/mojohaus/
And Mojo's Maven Plugin for GWT has been hosted on GitHub for a while: https://github.com/gwt-maven-plugin/gwt-maven-plugin
So the closing of CodeHaus shouldn't be what frightens you about the future of Mojo's Maven Plugin for GWT.
See also https://groups.google.com/d/topic/codehaus-mojo-gwt-maven-plugin-users/_WhNPQUNyd8

> I think one of the most useful aspects of the codeaus mojo is that it generates all your java resource classes from the ,css files. To start doing this by hand is going to be a P.I.T.A.
> 
> Is there a plan to do CSS generation in your plugin ?

I strongly believe those should be one-off tasks (same for `i18n`), so no there's no plan to add that to this plugin (at least for now; and even then, not in a way that would make it easy/pleasant to use as part of your build – i.e. really oriented to being called from the command line, as a thin wrapper around the GWT `InterfaceGenerator`). But the `InterfaceGenerator` doesn't work with GSS, and GSS is going to totally replace the old GWT-CSS syntax by the end of the year (it was planned for 2.8, but finally postponed to let more time for people to migrate), so it's actually more likely that it'll never happen, unless the `InterfaceGenerator` is updated to accept GSS as input.

> or is there a new way that I'm obviously not aware of ?

You can either call the `InterfaceGenerator` by hand, or through the [`maven-antrun-plugin`](https://maven.apache.org/plugins/maven-antrun-plugin/). The doc for the `InterfaceGenerator` can be found at http://www.gwtproject.org/doc/latest/DevGuideClientBundle.html#Automatically_generating_interfaces
See #18 for how to run it through the Apache Maven AntRun Plugin.

**Comment by biancashouse** [comment]
Music to my ears.
I've been using the mojo so long now that I hadn't noticed InterfaceGenerator.
All my mvn goals get run by ant scripts already and my poms do sometimes use AntRun, so it'll be nice to be able to separate out the CSS generation stuff and remove some of the pom complexity - I totally agree with that separation.
Your detailed response is really appreciated. Thanks.
