### ISSUE TITLE
No source code is available for type

### ISSUE THREAD

**Issue by hpehl** [tbroyer/gwt-maven-plugin#28]
I have setup a GWT multi maven projects with a couple of gwt-libs and one gwt-app [1]. However I just can't manage to compile / run the GWT app. When executing `gwt:compile` it keeps saying `No source code is available for type ... did you forget to inherit a required module?` I double-checked the jar files to contain the GWT module and the source files. From the output I can see that the modules are recognized and loaded.

I compared my setup to a project created using the `modular-webapp` archetype, but cannot find any fundamental differences. I also looked at the samples form the `src/it` folder. The only difference I can tell is that my app is a client-only app (no server side code). 

What am I doing wrong? Would be great if you could take a quick look whether I just mis-configured the plugin or whether there's something wrong in the plugin itself.

[1] https://github.com/hpehl/hal.next

**Comment by natros** [comment]
Hi.

The project complains about missing dependencies:

```
[ERROR] Failed to execute goal on project hal-processors: Could not resolve dependencies for project org.jboss.hal:hal-processors:jar:0.0.2: Failure to find org.jgrapht:jgrapht-core:jar:0.9.2-hal 
```

But I think the real problem is that you are not using src/main/module.gwt.xml. For instance, your org/jboss/hal/Ballroom.gwt.xml is being ignored. The ballroom/target/classes/org/jboss/hal/Ballroom.gwt.xml is automatically generated by the plugin and includes the src/main/module.gwt.xml.

If you really want to use org/jboss/hal/Ballroom.gwt.xml instead of src/main/module.gwt.xml you have to add <moduleTemplate> to the plugin configuration.

**Comment by hpehl** [comment]
Thanks @natros, works like a charme! I didn't know that I have to use `module.gwt.xml` files to declare my GWT modules. They're quite handy, though. BTW my maven project uses APT to generate code which is picked up by the GWT compiler. 

@tbroyer Maybe it's worth to add some documentation in [1]. Coming from the Codehaus GWT maven module I wanted to reuse my existing GWT modules. However it's much more simpler to switch over to `module.gwt.xml` files. 

[1] https://tbroyer.github.io/gwt-maven-plugin/migrating.html

**Comment by tbroyer** [comment]
Yes, it really needs to be better documented (and not only in the _migrating_ page). I'll leave this issue open for now as a reminder (aka repurposing as a documentation issue).

Thank you both for the feedback and early adoption.

**Comment by tbroyer** [comment]
In retrospect, I think I expected `resources:resources` to overwrite the module file generated by `gwt:generate-module`. Maybe it work with some version of the maven-resources-plugin (default one depending on the Maven version) and not with others. Anyway, this is now documented eb80130351467f6d1b54b856d1390459b6c38b9d
