### ISSUE TITLE
Working with non-standard directory structure

### ISSUE THREAD

**Issue by Dominator008** [tbroyer/gwt-maven-plugin#37]
Does the module description have to be "src/main/module.gwt.xml"? Can I get this plugin to work with a handwritten .gwt.xml file in an arbitrary location?

**Comment by ibaca** [comment]
Explained in the [migration guide](https://tbroyer.github.io/gwt-maven-plugin/migrating.html) just add `<skipModule>true</skipModule>` to disable the gwt:generate-module goal and point moduleName to your handwritten module. For example https://github.com/ibaca/rxjava-gwt/blob/master/pom.xml#L82

**Comment by tbroyer** [comment]
And if you want to benefit from `gwt:generate-module` but put your module file somewhere else, you can set [`moduleTemplate`](https://tbroyer.github.io/gwt-maven-plugin/generate-module-mojo.html#moduleTemplate) (be careful if you set `moduleTemplate` somewhere in your `src/main/java` or `src/main/resources`, `resources:resources` is likely to overwrite the generated file so you'll have to declare an explicit [`<resource>`](https://maven.apache.org/pom.html#Resources) that `<excludes>` it.

**Comment by Dominator008** [comment]
Thanks, moduleTemplate seems to work.
Another question: can you include an arbitrary .html page in the compiled .war archive? Right now it only consists of the compiled .js file, but not the .html file under public/.
My use case is here:
https://github.com/google/closure-compiler/pull/1258/files

**Comment by tbroyer** [comment]
For reference, see discussion in #8 (and in the Closure Compiler PR you linked to).
