### ISSUE TITLE
Resources issue

### ISSUE THREAD

**Issue by branflake2267** [tbroyer/gwt-maven-plugin#46]
I get a 404 when it's requesting the Project.html resource in this config. 

I can't get `mvn gwt:devmode` to work...

I'm curious why I can't get this to work. Might be I'm to tired at the moment. I had it working with a different naming, but won't work for me. 
```
mvn archetype:generate \
-DarchetypeRepository=https://oss.sonatype.org/content/repositories/snapshots \
-DarchetypeGroupId=com.github.branflake2267.archetypes \
-DarchetypeArtifactId=gwt-basic-archetype \
-DarchetypeVersion=2.0-SNAPSHOT \
-DgroupId=com.example.sandy \
-DartifactId=sandy
```
I should have Eclipse snapshot ready. I'm uploading my changes to the snapshot repo now.

**Comment by tbroyer** [comment]
See #8. You should either use war packaging and configure the goals you want, or move your static resources in the "public path" of the GWT module.

**Comment by branflake2267** [comment]
ah ha, thanks.
