### ISSUE TITLE
Documentation: Project structure

### ISSUE THREAD

**Issue by branflake2267** [tbroyer/gwt-maven-plugin#47]
May I suggest adding the project structure to the documentation. This would help dev visualize all the resource locations. I can help do this in the next week. 

Such as
```
src/[package]
src/main/super
src/main/module.gwt.xml - module descriptor
src/main/webapp
target/gwt/...
```

**Comment by tbroyer** [comment]
Fixed by d5f9111d9eca7e6aa8125d2ccc1b002cc0ee220b

Note that there's no `src/main/webapp` expected in the default configuration.
