### ISSUE TITLE
Multiple GWT modules in one maven module

### ISSUE THREAD

**Issue by hpehl** [tbroyer/gwt-maven-plugin#57]
I'm wondering if it's possible to have two GWT modules with two different entry points in one maven module. I know I could setup two different maven modules (using packaging `gwt-app`) each having its own entry point. But I'd like to use common static resources like CSS, javascript and images for both entry points.

**Comment by tbroyer** [comment]
It's possible to configure 2 `compile` executions, but not to pass several module names to a single `compile` execution. That could possibly be added though (most likely through another goal)

But sharing resources could also be done by sharing a dependency, given that GWT loads everything from the classpath.

**Comment by ibaca** [comment]
Still think that forcing one and only one module is a bit confusing (only confusing in non-standard cases, but still confusing), not sure the advantages. For example using <automod> (only one) to use the auto generated module, and <modules><module> (multiples) to enable traditional module definition will be (IMO) easier to understand/predict-the-result coming from mojo plugin.

**Comment by tbroyer** [comment]
Thinking about it, supporting multi modules is not as simple as it may sound: how do you configure the moduleName vs. moduleShortName? (that's used for staleness checks; and what if results vary depending on module order? that'd influence the way you configure things) how do you do staleness checks given you can't really subset the input sources? (this is not really different than using several compile executions though) and more importantly, would you only recompile changed modules or recompile them all as soon as one is detected as stale? (what if one version of GWT has a bug and results vary depending on the compiled modules? should the behavior be configurable?)

I don't really know the exact implications on compiling time, including across versions (remember the plugin aims at support the latest stable release, previous stable release, and latest snapshot), and with incremental compilation.

Feel free to send a PR, but I'd rather leave this for later.

**Comment by hpehl** [comment]
I agree @tbroyer. In the meantime I found another solution. Instead of two different entry point I use two different places / activities. Actually that fits better to my use case. 

So I don't mind closing or put on hold.

**Comment by BedunkevichE** [comment]
Hi
any news about this theme - supporting multi modules?
Decided to change Mojo gwt plugin to maven gwt plugin and faced with this problem
i my application there are 4 modules with different entry points and  different gwt.xml files.
and cant option it in  pom like  in mojo's.

the reason of changing plugins is  that  your plugin can add hash/modified info to  *.nochace.js during compilation  and it would help me to solve  caching problem in  deploy/redeploy process.
so maybe  is there any window  how to   configure multi  modules?
have read about several executions but  havent undestand how to configure it in pom depend on modules.
thanks for reply

**Comment by tbroyer** [comment]
See https://groups.google.com/d/msg/google-web-toolkit/sjh6AGfeCKQ/Dp2fNL6HAQAJ for how to configure several executions.
