### ISSUE TITLE
How to add resources (html/css etc) to the generated gwt war

### ISSUE THREAD

**Issue by jschoedt** [tbroyer/gwt-maven-plugin#58]
Is there any way to add resources (html/css etc) to the generated gwt war?

My use-case is that I have a simple maven structure. gwt-app + web-app. I have been using thymeleaf html templates for a while (located in web-app) but now we have started to use Errai templates. The beauty is that Errai templates can be mixed in our thymeleaf templates so the front-end guy can easily develop his html just using simple html files. But now I need to put the html files inside the gwt-project for Errai to compile, so I need those html files in the gwt-app war so the final web-app war contains them for thymeleaf to work. But it is like they get filtered out of the gwt war?

**Comment by tbroyer** [comment]
Depending on your needs (whether you want the templates a "web resources" in your final WAR, or only accessible as "java resources" through the classloader, i.e. in `WEB-INF/classes` or `WEB-INF/lib`) you can:

 * put them in your gwt-app in the [_public path_](http://www.gwtproject.org/doc/latest/DevGuideOrganizingProjects.html#DevGuideModules)
 * put them in a shared Java library that both the gwt-app and web-app depend on
 * put them in a shared library, but use it as an [_overlay_](https://maven.apache.org/plugins/maven-war-plugin/overlays.html) in the web-app to put the content wherever you want it.
