### ISSUE TITLE
Create an empty directory for src/test/java in archetype

### ISSUE THREAD

**Issue by branflake2267** [tbroyer/gwt-maven-plugin#63]
Importing project created from archetype has a build path issue. 

<img width="413" alt="screen shot 2016-10-02 at 12 26 34 pm" src="https://cloud.githubusercontent.com/assets/1326504/19023154/e359f05c-889b-11e6-9bfa-0f6288424336.png">

Could you create a empty directory for src/main/test in the archetype so Eclipse doesn't have an error initially in the build path. In the archetypes I create I throw an empty directory into them so it doesn't have an error after import.

**Comment by ibaca** [comment]
I used this
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-antrun-plugin</artifactId>
    <version>1.7</version>
    <executions>
        <execution>
            <id>make-standard-directory-layout</id>
            <phase>validate</phase>
            <configuration>
                <tasks>
                    <mkdir dir="${project.basedir}/src/" />
                    <mkdir dir="${project.basedir}/src/main" />
                    <mkdir dir="${project.basedir}/src/main/java" />
                    <mkdir dir="${project.basedir}/src/main/resources" />
                    <mkdir dir="${project.basedir}/src/test" />
                    <mkdir dir="${project.basedir}/src/test/java" />
                    <mkdir dir="${project.basedir}/src/test/resources" />
                </tasks>
            </configuration>
            <goals>
                <goal>run</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

**Comment by tbroyer** [comment]
Wrong repository; you probably meant tbroyer/gwt-maven-archetypes.

But even then, I don't think it's a problem with the archetypes, and more with Eclipse or the GWT Plugin for Eclipse.

 1. IntelliJ has a feature to automatically create those "missing" directories when importing a project (so Eclipse could possibly do the same)
 2. Git only stores files, so committing the generated project and then cloning it / checking it out back would lose the directories and you'd have the same issue in Eclipse. So this is not really an issue with the archetype, or with Git, but more with Eclipse.

**Comment by branflake2267** [comment]
hm, gotcha. It's a m2e import issue. It's not blocking so I'll look at either patching or enhancing the GWT Eclipse Plugin to create them. https://github.com/gwt-plugins/gwt-eclipse-plugin/issues/238
