### ISSUE TITLE
m2e not generating module.gwt.xml for gwt-lib

### ISSUE THREAD

**Issue by dnouls** [tbroyer/gwt-maven-plugin#68]
I have a project with multiple gwt-lib modules and one gwt-app. 
The module.gwt.xml is properly generated for the gwt-app but not for the gwt-lib modules.
Is this a problem of the gwt maven plugin or the gwt eclipse plugin ? Or maybe something I need to add to the pom.xml ?

**Comment by tbroyer** [comment]
`generate-module` is properly configured to run in M2Eclipse: https://github.com/tbroyer/gwt-maven-plugin/blob/1.0-rc-6/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
and is of course properly configured to run in the `gwt-lib` lifecycle, at the same `generate-resources` phase than in the `gwt-app` lifecycle: https://github.com/tbroyer/gwt-maven-plugin/blob/1.0-rc-6/src/main/resources/META-INF/plexus/components.xml#L96

It must be a problem with M2Eclipse and/or the GWT Eclipse Plugin (I see it has some configuration for the `generate-module` goal: https://github.com/gwt-plugins/gwt-eclipse-plugin/blob/b49692c80b09871b0f645a84cb54b58bd0ff72e0/plugins/com.gwtplugins.gdt.eclipse.maven/lifecycle-mapping-metadata.xml#L27 & https://github.com/gwt-plugins/gwt-eclipse-plugin/blob/b49692c80b09871b0f645a84cb54b58bd0ff72e0/plugins/com.gwtplugins.gwt.eclipse.wtp.maven/lifecycle-mapping-metadata.xml#L27)
