### ISSUE TITLE
Environment variable from parent pom

### ISSUE THREAD

**Issue by vegegoku** [tbroyer/gwt-maven-plugin#70]
Hi
i have  gwt application that uses the multi-module archetype, i have been writing test cases and executing them with no issue until i had to use the environment variables, after i researched how i can pass environment variable for the test cases i found that i can do the following :

```
<pluginManagement>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.17</version>
          <configuration>
            <environmentVariables>
              <CONFIG_PATH>${user.dir}/testConfig</CONFIG_PATH>
            </environmentVariables>
          </configuration>
        </plugin>
</pluginManagement>
```
since i defined the environment variable in the plugin management section it is supposed to be shared with all sub-modules, and all sub-modules were able to fetch the environment variable using `System.getEnv().get("CONFIG_PATH")`  except for the tests of my client modules, after a lot of trail and error i found that if i change the packaging type of my client modules from `gwt-lib` to `jar` every thing works as it supposed to be and the test fetches the environment variable with no issues.

so i thought it might be something related to the `gwt-maven-plugin`, so i decided to try and duplicate my environment variables into the `gwt-maven-plugin` and revert back to `gwt-lib` packaging like this : 

```
<packaging>gwt-lib</packaging>
...

              <plugin>
                <groupId>net.ltgt.gwt.maven</groupId>
                <artifactId>gwt-maven-plugin</artifactId>
                <version>1.0-rc-6</version>
                <extensions>true</extensions>
                <configuration>
                    <moduleName>someModuleName</moduleName>
                    <environmentVariables>
                        <CONFIG_PATH>${user.dir}/testConfig</CONFIG_PATH>
                    </environmentVariables>
                </configuration>
            </plugin>
```

after doing so every thing worked as expected but it lead to the conclusion that the` gwt-maven-plugin` with `gwt-lib` packaging is preventing the module from inhering the parent pom plugin management configuration.

maybe because the `gwt-maven-plugin` is overriding the surefire plugin configuration. 
i can go with the current solution but i prefer not to duplicate these configuration.

what could be the solution for such issue?

**Comment by tbroyer** [comment]
The `gwt-lib` and `gwt-app` packagings don't use `surefire:test`, but `gwt:test`, which relies on Surefire but is tailored for GWTTestCase; see https://tbroyer.github.io/gwt-maven-plugin/lifecycles.html

This doesn't prevent you from declaring the configuration in the parent POM, but you cannot share it with the maven-surefire-plugin (blame Maven for that).

```xml
<pluginManagement>
  <plugins>
    <plugin>
      <groupId>net.ltgt.gwt.maven</groupId>
      <artifactId>gwt-maven-plugin</artifactId>
      <version>1.0-rc-6</version>
      <extensions>true</extensions>
      <configuration>
        <environmentVariables>
          <CONFIG_PATH>${user.dir}/testConfig</CONFIG_PATH>
        </environmentVariables>
      </configuration>
    </plugin>
    <plugin>
      <artifactId>maven-surefire-plugin</artifactId>
      <version>2.17</version>
      <configuration>
        <environmentVariables>
          <CONFIG_PATH>${user.dir}/testConfig</CONFIG_PATH>
        </environmentVariables>
      </configuration>
    </plugin>
```
