### ISSUE TITLE
Errai framework 

### ISSUE THREAD

**Issue by masterdany88** [tbroyer/gwt-maven-plugin#71]
Is this plugin works with Errai Framework from redhat? Specially I am interested in maven multi module project. Please help? If this work, can you prepare errai archetype to generate multi module maven project ?

**Comment by tbroyer** [comment]
There's no reason it wouldn't _a priori_ work with Errai, and there are likely users who use it with Errai, but I have zero experience with Errai so can't say much.

You should ask the Errai community / developers.

/cc @csadilek
