### ISSUE TITLE
Logging GWT Compilation Classpath when using compile goal

### ISSUE THREAD

**Issue by dfht** [tbroyer/gwt-maven-plugin#72]
Is it possible to log the GWT Compilation Classpath so as to see what is happening when it's too long on windows? I can't find a way of doing it. I think the Mojo plug-in had a printJavaCommandOnError flag you could set, but I can't find anything for your plug-in at present.
I guess I can always set debug ports and connect from Eclipse with a break-point on ProcessBuilder, but it'd better if there was simple way (maybe there is but I don't know it so please let me know if there is!).....

Alternatively, if nothing can log this at present, could you tell me which jars etc. go on the GWT compiler class-path when using your compile goal? Is it the entire transitive path of the war project (the one I do the compile from) or is it more selective? I think it's the entire path for the Mojo plug-in but I'm hoping that for yours it is somehow more selective (e.g. just those with maven-source attached source or that define GWT modules or whatever clever criteria can be applied to avoid this being unnecessarily long.......)? I need to know as one of my goals in switching to your plug-in is the avoidance of these class-path length issues for large systems (and our systems do drag in a lot of jars).........

**Comment by tbroyer** [comment]
This has been added in 7e871e0c68dc578e3b58d850ee544003b4f3ded2 but not yet released; you can try 1.0-SNAPSHOT from Sonatype OSSRH (`https://oss.sonatype.org/content/repositories/snapshots`)

To answer your question, all compile dependencies (i.e. scopes `compile`, `system` and `provided`) are added to the classpath, and `gwt-dev` needs to be declared as a project dependency. If you want to cut down the number of entries in the classpath, then cut down the number of project dependencies; splitting client and server code into separate Maven modules generally helps a lot.

Have a look at https://tbroyer.github.io/gwt-maven-plugin/migrating.html when migrating from Mojo's Maven Plugin for GWT; see also https://tbroyer.github.io/gwt-maven-plugin/codeserver.html which talks a bit about scopes.
