### ISSUE TITLE
Make the defaults for gwt:compile options the same as those of standalone GWT compiler

### ISSUE THREAD

**Issue by dfht** [tbroyer/gwt-maven-plugin#75]
I cannot get your plug-in to GWT compile my system, despite the fact that a standalone compilation (e.g. using an Eclipse launcher that just uses GWT defaults) just works.

I'm not sure why well established defaults are overridden, but I'd prefer it if they were not.
Not setting the localWorkers for example leads to the plug-in using 8, which then causes my compile to fail due to insufficient heap size (normally 3GB is enough, but not with 8 workers!). 
Strangely, setting localWorkers to 1 also fails as well, but setting to zero causes it to use 8 again! I'm not sure what GWT compiler does with this setting by default. All I know is that it doesn't set it to 1, as that also fails in a standalone GWT compile!

I'm also finding it tricky to see what values it is using for various options under the covers. I just want to leave it with default GWT compiler settings that work fine for me, and coaxing this plug-in to use defaults is proving to be a time consuming trial and error process at present.....

In detail:

Setting (in your plug-in or standalone compiler invocation) 

-optimize 0 -localWorkers 1

Always fails.

Setting no extra options in a straight standalone GWT compile works.

I just want to invoke your plug-in with the equivalent of not overriding any GWT compiler options!
Is there a way to do this? Of course it would help if the GWT main web documentation actually specified what all of the defaults are!!!!!!!! (that bit is obviously not your issue)!, but the overriding of defaults/difficulty of just using it without extra arguments being set for you behind the scenes (in my opinion at least)  is.......

**Comment by tbroyer** [comment]
The default is `-localWorkers 1`; see https://github.com/gwtproject/gwt/blob/2.8.0/dev/core/src/com/google/gwt/dev/util/arg/ArgHandlerLocalWorkers.java#L33-L36 and https://github.com/gwtproject/gwt/blob/2.8.0/dev/core/src/com/google/gwt/dev/PermutationWorkerFactory.java#L335-L338  
Maybe you need to set JVM memory args in [`jvmArgs`](https://tbroyer.github.io/gwt-maven-plugin/compile-mojo.html#jvmArgs)?

FWIW, this plugin sets very few options, besides output directories:  
https://github.com/tbroyer/gwt-maven-plugin/blob/7b74f5b17423fe93064954ed7d226021c4fd17b6/src/main/java/net/ltgt/gwt/maven/GwtOptions.java  
 * `-logLevel` (default depends on Maven log level, would be `INFO` by default),
 * `-style` (defaults to `OBFUSCATED`),
 * `-draftCompile` or `-optimize` (defaults to `-optimize 9` which is the same as [GWT's default](https://github.com/gwtproject/gwt/blob/2.8.0/dev/core/src/com/google/gwt/dev/util/arg/OptionOptimize.java#L26)), and
 * `-sourceLevel` (defaults to `${maven.compiler.source}`, which is not set by default, so left to GWT's default)
 * `gwt:compile` also passes `-failOnError` if you set `<failOnError>true</failOnError>` or `-Dgwt.failOnError=true`

I might very-well revise this to actually default to not passing those options at all to GWT, but I believe those are "sane defaults" (I admit `-localWorkers` might not be everyone's favorite, maybe I should try using input values similar to Maven's own `-T`, also used by Surefire and Failsafe: https://maven.apache.org/surefire/maven-surefire-plugin/examples/fork-options-and-parallel-execution.html, so I could default to GWT's default and let people use `1C` to get the current behavior)

**Comment by dfht** [comment]
No, I do set the jvmArgs.
I look at the classes you point me at as the code doesn't lie (unlike the GWT docs) :).
It really is a mystery as without specifying localWorkers it works and specifying it as 1 fails (for straight GWT compiler invocation without Maven or your plug-in being involved)!

**Comment by dfht** [comment]
Here's what fails:

<plugin>
  				<groupId>net.ltgt.gwt.maven</groupId>
 				 <artifactId>gwt-maven-plugin</artifactId>
 				 <version>1.0-rc-6</version>
  				<extensions>true</extensions>
				<executions>
					  <execution>
							<goals>
			  					 <goal>compile</goal>
							</goals>
		  			</execution>
				</executions>
  				<configuration>
    				<moduleName>com.serisys.gwt.ui.adyptwebmain.AdyptWebMain</moduleName>
 				    <webappDirectory>${webappDirectory}</webappDirectory>
					<jvmArgs>
						<jvmArg>-Xms1024m</jvmArg>
						<jvmArg>-Xmx3072m</jvmArg>
					</jvmArgs>
					<skipModule >true</skipModule >
					<logLevel>WARN</logLevel>
					<optimize>0</optimize>
					<style>OBFUSCATED</style>
					<localWorkers>1</localWorkers>
					
  				</configuration>
	 	</plugin>

**Comment by dfht** [comment]
Sorry, try again :)
`<plugin>
  				<groupId>net.ltgt.gwt.maven</groupId>
 				 <artifactId>gwt-maven-plugin</artifactId>
 				 <version>1.0-rc-6</version>
  				<extensions>true</extensions>
				<executions>
					  <execution>
							<goals>
			  					 <goal>compile</goal>
							</goals>
		  			</execution>
				</executions>
  				<configuration>
    				<moduleName>com.serisys.gwt.ui.adyptwebmain.AdyptWebMain</moduleName>
 				    <webappDirectory>${webappDirectory}</webappDirectory>
					<jvmArgs>
						<jvmArg>-Xms1024m</jvmArg>
						<jvmArg>-Xmx3072m</jvmArg>
					</jvmArgs>
					<skipModule >true</skipModule >
					<logLevel>WARN</logLevel>
					<optimize>9</optimize>
					<style>OBFUSCATED</style>
					<localWorkers>1</localWorkers>
					
  				</configuration>
	 	</plugin>`

**Comment by dfht** [comment]
Damn, what's happening with the formatting here :). How do I just paste some XML in?

**Comment by tbroyer** [comment]
> Damn, what's happening with the formatting here :). How do I just paste some XML in?

https://help.github.com/articles/creating-and-highlighting-code-blocks/

(let me try to fix your comments)

**Comment by dfht** [comment]
Ok Thomas.
To cut a long story short, localWorkers=1 and optimize=0 (or 1) fails.
However, going with what you said are the defaults (and looking at the classes you pointed me at and related ones) and using localWorkers=1 and optimize=9, it works! This surprises me, as I would have thought that a lower value for optimize would mean less analysis of the source and hence lower memory usage....  What am I missing here? Why does a higher optimize use less memory? I guess I've misinterpreted what optimize means  - I thought it meant optimize the generated JavaScript, but perhaps it means optimize the process of compiling (e.g. memory usage) ;)!

**Comment by dfht** [comment]
I'm still dubious about that localWorkers=8 default though ;)

**Comment by dfht** [comment]
Thanks again, and I'll switch to the snapshot version for the better debug logging.
Obviously it's up to you what you do about those defaults :)... If you feel like explaining the 'optimize' argument (0 memory > 9 memory use)  then that's be nice, but no worries if not...

**Comment by tbroyer** [comment]
Added ability to specify localWorkers relative the number of CPU cores in b928fc096994425c6b45bda5d8fc8a3d44f2a6b3, dropped default to using the number of CPU cores (i.e. value `1C`) in 32299f2543190359d1960ae2f6208f7a08b921d7.

`logLevel`, `failOnError`, `optimize`, `style`, and `localWorkers` now all default to what GWT would default to (i.e. not setting those means that no corresponding argument will be passed to GWT).
That only leaves `sourceLevel` and `draftCompile` with default values, and `sourceLevel` will generally actually default to no value (as explained in https://github.com/tbroyer/gwt-maven-plugin/issues/75#issuecomment-282351422)
