### ISSUE TITLE
LICENSE not found

### ISSUE THREAD

**Issue by ibaca** [tbroyer/gwt-maven-plugin#80]
😄 just a reminder, it's your code and looks like no license means exclusive copyright which is totally right. I just reviewing my projects and looking at your repos to see what you use in libs, showcases, etc. and found that this one has no LICENSE file.

**Comment by ibaca** [comment]
Ok, it is in the pom, anyway, I have added the LICENSE file to the mojo plugin too. Just to make github happy and show more info about the license in the main page. Is this ok? I suppose it is. I'm just a bit afraid about adding a LICENSE file on this ancient project. The mojo plugin have the license in the pom too.

**Comment by tbroyer** [comment]
Thanks, done.
