### ISSUE TITLE
How do you get JsInterop exports working for non native types?

### ISSUE THREAD

**Issue by dmg46664** [tbroyer/gwt-maven-plugin#81]
Couldn't see an easy answer on the documentation:
https://tbroyer.github.io/gwt-maven-plugin/codeserver.html

I know that it has to be accommodated even in 2.8.0 due to [optimization concerns](https://groups.google.com/d/msg/google-web-toolkit-contributors/_eHExf0yn-A/68TFpnlPEQAJ) which have tripped others up and so [advised to specify `generateJsInteropExports` as a compiler argument](https://github.com/gwtproject/gwt-site/issues/192)

Here are my poor cobbled attempts by merging:
https://github.com/tbroyer/gwt-maven-plugin/issues/22
and the above advice.
```
<plugin>
        <groupId>net.ltgt.gwt.maven</groupId>
        <artifactId>gwt-maven-plugin</artifactId>
        <configuration>
          <moduleName>com.project.App</moduleName>
          <moduleShortName>app</moduleShortName>
          <moduleTemplate>${project.basedir}/src/main/App.gwt.xml</moduleTemplate>
          <compilerArgs>
            <compileArg>-XjsInteropMode</compileArg>
            <compileArg>-generateJsInteropExports</compileArg>
            <compileArg>JS</compileArg>
          </compilerArgs>
          <codeserverArgs>
            <arg>-XjsInteropMode</arg>
            <arg>-generateJsInteropExports</arg>
            <arg>JS</arg>
          </codeserverArgs>
          <generateJsInteropExports>true</generateJsInteropExports>
          <incremental>true</incremental>
          <jsInteropMode>JS</jsInteropMode>
        </configuration>
      </plugin>
```

Here's what it looks like in Chrome DevTools. Note the mangled names for `address` and `name` in the javascript inspector.

<img width="1354" alt="screen shot 2017-04-09 at 11 28 02" src="https://cloud.githubusercontent.com/assets/1296603/24836606/eb5244d8-1d17-11e7-8587-45953d5cc9de.png">
 

Tried with and without `@JsProperty` even though the documentation said it wasn't necessary.
```
@JsType
public class Person {

  @JsProperty
  public String name;
  @JsProperty
  public String address;

  public Person(String name, String address) {
    this.name = name;
    this.address = address;
  }
}
```

**Comment by TDesjardins** [comment]
Are you using GWT 2.8.0?

**Comment by dmg46664** [comment]
@TDesjardins Yes, though thank you for checking. There is lambdas in the client module so I'm guessing it won't compile with 2.7.0.

If it helps I'm using this starter project:
https://github.com/dmg46664/gwt-storage-objectify

**Comment by dmg46664** [comment]
My continued tale of woe...

I worked out how to log the command arguments and read the `gwt-maven-plugin` code 

```
$ mvn gwt:codeserver -pl *client -am -e -X | grep Arguments
[DEBUG] Arguments: com.google.gwt.dev.codeserver.CodeServer -logLevel DEBUG -workDir /Users/dmg46664/IdeaProjects/borrowingsucks/target/gwt/codeserver -sourceLevel 1.8 -failOnError -launcherDir /Users/dmg46664/IdeaProjects/borrowingsucks/target/gwt/launcherDir -allowMissingSrc -src /Users/dmg46664/IdeaProjects/borrowingsucks/gwt-storage-objectify-client/src/main/java -src /Users/dmg46664/IdeaProjects/borrowingsucks/gwt-storage-objectify-shared/src/main/java com.project.App
```

Couldn't find [illuminating examples of configuration in the archetypes](https://github.com/tbroyer/gwt-maven-archetypes/blob/master/modular-webapp/pom.xml)

Given I could see `@Parameter` used for the codeserver and compiler arguments, I went looking for [how best to configure this from the Apache docs](https://maven.apache.org/guides/mini/guide-configuring-plugins.html)

Saw the `<options><option>` nested pattern. Didn't work.

Found out I can get help on the arguments (but doesn't provide syntax).

```
$ mvn gwt:help -Ddetail=true -Dgoal=compile
```

Found out [the difference in parameter formatting between lists and arrays](http://stackoverflow.com/questions/14120535/what-is-the-syntax-for-a-maven-parameter-of-type-string)

Left a bitchy comment [searching for maven xml configuration validation](http://stackoverflow.com/questions/40599913/how-does-plugin-validation-work-in-maven-and-why-does-it-build-my-project-with#)

Decided to try and debug the `gwt-maven-plugin` build since I still couldn't figure out the secret sauce by other means. Turns out this [is pretty easy to do].(http://stackoverflow.com/questions/2973888/debug-a-maven-plugins-execution-in-a-maven-web-project)

Looking at what parameters were and were not available in `CodeServerMojo.java` I was able to conclude that:

**Putting the configuration in the client pom.xml does not make it through to execution when running:** ❗️ 

`mvn gwt:codeserver -pl *client -am -e`

So sticking the following

```
<codeserverArgs>
              <arg>-generateJsInteropExports</arg>
            </codeserverArgs>
            <compilerArgs>
              <arg>-generateJsInteropExports</arg>
            </compilerArgs>
```
Sticking this in the parent pom got the arguments across for the code server.


```
$ mvn gwt:codeserver -pl *client -am -e -X | grep Arguments
[DEBUG] Arguments: com.google.gwt.dev.codeserver.CodeServer -logLevel DEBUG -workDir /Users/dmg46664/IdeaProjects/borrowingsucks/target/gwt/codeserver -sourceLevel 1.8 -failOnError -launcherDir /Users/dmg46664/IdeaProjects/borrowingsucks/target/gwt/launcherDir -generateJsInteropExports -allowMissingSrc -src /Users/dmg46664/IdeaProjects/borrowingsucks/gwt-storage-objectify-client/src/main/java -src /Users/dmg46664/IdeaProjects/borrowingsucks/gwt-storage-objectify-shared/src/main/java com.project.App
```

However, this has not solved the underlying issue as the field names are still not available in javascript ❌ 

I was wondering whether it had to do with the `compilerArgs`. However, I can't manage to trigger breakpoints in `CompileMojo.java` but presumably this would only be triggered in a standalone compilation, so isn't likely the cause.

**Comment by TDesjardins** [comment]
I am asking because in GWT 2.8.0 you don't need arg jsInteropMode. Have a look at https://github.com/TDesjardins/gwt-ol3/blob/master/pom.xml#L107
When I uncomment this line jsexports works for me.

**Comment by dmg46664** [comment]
@TDesjardins Thanks for performing this test! ⭐️ 

Searching your code [for JsType](https://github.com/TDesjardins/gwt-ol3/search?p=4&q=JsType&type=&utf8=%E2%9C%93) I see that mainly you are using `isNative = true`.

As stated, my problem is with non-native types. Do you have any examples of exposing properties on non-native types?

**Comment by TDesjardins** [comment]
I know. I had some none native types before and because of that I know that it works. I changed then the code and after that I commented the exports arg. By the way your JSCode could be helpful.

**Comment by dmg46664** [comment]
@TDesjardins - Which javascript code are you referring to because there isn't any? The `Person` class is all Java. I'm merely breakpointing at a point after I've instantiated it, then inspecting it in Chrome Dev tools inspector expecting to see the field names persisted, which they haven't.

**Comment by tbroyer** [comment]
Hi, back from the weekend and trying to unravel this thread. I'm sorry you had to go through all those hops to finally find how to pass the arguments down to the code server, but I don't want the plugin's documentation to fill the gaps in the (rather bad) Maven documentation (I don't recommend using Maven anyway); the fact that the plugin is independent from the GWT version also means that you have to go look at GWT for the arguments you want to pass.

Here are a few pointers to documentation that'd have hinted in the good direction:
 * Documentation for the arguments to pass to GWT can be found at http://www.gwtproject.org/doc/latest/DevGuideCompilingAndDebugging.html#DevGuideCompilerOptions and http://www.gwtproject.org/articles/superdevmode.html#Starting; and/or you can pass the `-help` argument (or any “broken” argument).
 * Configuring lists in Maven plugins is explained at https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Mapping_Lists (it explains, rather badly but still, that the child element's name is actually almost useless –unless it matches some class in the same package as the mojo–, so you can use `<compilerArg>` or `<arg>` interchangeably)
 * https://tbroyer.github.io/gwt-maven-plugin/codeserver.html explicitly says the codeserver is configured in the root POM (and not in the `client` submodule's POM)

That being said, the plugin's documentation might benefit from having an example of configured arguments (in the _Usage_ page maybe?), so feel free to send in a patch.

Given that you managed to pass `-generateJsInteropExports` to the codeserver, I'm going to close this issue. If you still have issues with getting your JS types exported, please bring them on the [GWT forum](https://groups.google.com/forum/#!forum/google-web-toolkit).

**Comment by dmg46664** [comment]
@tbroyer - Thanks for a very thorough follow up.

When I see walls of text I don't tend to read from start to finish, in this case not making it through the first sentence. :-)

I've added [a comment to the client pom of the starter project I used](https://github.com/freddyboucher/gwt-storage-objectify/pull/3/commits/4f7155172b7708f4a73f201265ce56cd584f9dce#diff-f4e19dd640bd53fe872dd726cef20325). Would you be averse to something like this in the archetypes? If not, I will add it.

The most interesting part of your reply was that you don't recommend Maven. Do you use this plugin with Gradle or some other build system?

**Comment by tbroyer** [comment]
> The most interesting part of your reply was that you don't recommend Maven. Do you use this plugin with Gradle or some other build system?

I do actively recommend using Gradle (or Bazel/Buck/Pants if you feel adventurous).  
This plugin is a Maven plugin (because while I don't recommend Maven, I still do use it on some projects; and Maven users deserve something good too – I also happen to have grown my understanding and subsequently rejection of Maven by working on this plugin, and the MojoHaus one) and thus cannot be used with Gradle.  
I actually haven't (really) used GWT with Gradle (yet), but Gradle is flexible enough to make it really easy, and there actually are a couple plugins already to help you.  
To read more about my thoughts on Maven, see http://blog.ltgt.net/maven-is-broken-by-design/ and http://blog.ltgt.net/maven-is-broken-by-design-2/

**Comment by dmg46664** [comment]
Thanks! Had I seen a prototype working with Gradle, GWT and AppEngine I would have gone for that. Probably my nervousness in picking up GWT not having touched it in a couple of years, meant I was looking for something that just worked. Oh well. 🤔
