### ISSUE TITLE
How do you debug the GWT compiler using gwt-maven-plugin?

### ISSUE THREAD

**Issue by dmg46664** [tbroyer/gwt-maven-plugin#82]
I set a breakpoint in the constructor of the IntelliJ decompiled [`GwtAstBuilder`](https://github.com/gwtproject/gwt/blob/master/dev/core/src/com/google/gwt/dev/jjs/impl/GwtAstBuilder.java) which I figured sounds pretty critical to the whole parsing a language thing. 😄 

I thought then perhaps running maven in debug mode via

`$ mvndebug gwt:codeserver -pl *client -am -e`

and then connecting via remote debugging would allow me to hit the breakpoint. Alas not.

Any clues as to how to set this up?

**Comment by tbroyer** [comment]
The plugin will fork a new JVM when invoking GWT, so you have to pass the appropriate `-agentlib:jdwp=…` to the forked JVM (in the [`jvmArgs`](https://tbroyer.github.io/gwt-maven-plugin/codeserver-mojo.html#jvmArgs)) and then attach your debugger/IDE to the running process (aka “connecting via remote debugging”). I suggest using `suspend=y` in your JDWP options to have the JVM wait for you to connect your debugger before actually running.

**Comment by dmg46664** [comment]
For anyone who comes back here, I had success with the following:

```
<jvmArgs>
              <!--http://javahowto.blogspot.co.uk/2010/09/java-agentlibjdwp-for-attaching.html-->
              <arg>-agentlib:jdwp=transport=dt_socket,address=localhost:8000,server=y,suspend=y</arg>
</jvmArgs>
```

**Comment by tbroyer** [comment]
FWIW, I generally just copy/paste what my IDE tells me to use.

**Comment by p4535992** [comment]
Same problem, but the solution here seem not to work. There is some more detailed article about it ?

**Comment by tbroyer** [comment]
I encourage you to ask in https://groups.google.com/g/google-web-toolkit, explaining what you want to achieve, and what/how you did try that didn't work.
