### ISSUE TITLE
IntelliJ compatiblity: Document how to set up the e2e example so GWT super dev mode works in IntelliJ IDEA too

### ISSUE THREAD

**Issue by ge0ffrey** [tbroyer/gwt-maven-plugin#83]
IntelliJ's GWT support works with the old maven-gwt-plugin, but on first sight it doesn't work with this new one:
  https://youtrack.jetbrains.com/issue/IDEA-171158

If there's a way to make it work so we can debug GWT client classes with IntelliJ's super dev mode support, it should be documented.

**Comment by tbroyer** [comment]
Pull request welcome! (though I suspect something would have to be done on the IDE side anyway to support the custom packagings)
Maybe documenting equivalent configurations to the custom packagings but with standard `jar` and `war` (or `pom`?) would be enough? (and IDE agnostic, which I would much prefer)

**Comment by ge0ffrey** [comment]
So far, the best I can come up with in IntelliJ is a run configuration that does a "mvn clean install" and then deploys the war to the app server (WildFly). I haven't been able to start GWT super dev mode yet, despite a number of configuration tries.

I suspect that maybe it's not even possible until they fix this issue:
  https://youtrack.jetbrains.com/issue/IDEA-171158
but meanwhile we should indeed document the best approach (even if that's that "mvn clean install" approach).

**Comment by ge0ffrey** [comment]
Looks like IntelliJ 2017.3 has fixed this issue (not yet released, I haven't tried it out yet).
