### ISSUE TITLE
Supporting Vert.x

### ISSUE THREAD

**Issue by vegegoku** [tbroyer/gwt-maven-plugin#84]
Recently i have been playing with vert.x, it was super easy to get an HttpServer up and running, so it came to my mind if i can run a GWT application on Vert.x, so i decided to try that, all i needed to do then was to copy the artifacts generated from the GWT compiler into the resources folder of my Vert.x module and made Vert.x httpServer serve static resources from it, then since this does not work with GWT-RPC i used restyGwt to make calls for the server.

now my question is, can we make the plugin compile artifacts to a specific folder in the project resources?
i mean to produce artifacts that goes into the resources folder instead of an exploded war.

and if this is doable will it still play nicely with the super-dev-mode?

**Comment by natros** [comment]
Use the gwt:codeserver and set the `<launcherDir>`  to point to a folder of your http server

**Comment by tbroyer** [comment]
> now my question is, can we make the plugin compile artifacts to a specific folder in the project resources?
> i mean to produce artifacts that goes into the resources folder instead of an exploded war.

See #34 

> and if this is doable will it still play nicely with the super-dev-mode?

It all depends on how Vert.x works and/or how you run it. When running `gwt:codeserver` with `<launcherDir>`, it'll generate a `*.nocache.js` (and will copy public resources), and those need to be served by the Vert.x HTTP server.
