### ISSUE TITLE
gwt:codeserver doesn't pick up changes under resources/ folder

### ISSUE THREAD

**Issue by freddyboucher** [tbroyer/gwt-maven-plugin#87]
Hi,
My *.gss files are under the **resources/** folder and when I run **gwt:codeserver**, any changes I do in these files are not picked up by the compiler.

Workaround: I moved my gss files under the **java/** folder.
Thanks.

**Comment by tbroyer** [comment]
[Maven resources](https://maven.apache.org/pom.html#Resources) may be filtered (`filtering`), relocated (`targetPath`) and/or have inclusion/exclusion patterns (`includes`/`excludes`), so they *have* to be processed by the maven-resources-plugin (or possibly your IDE); then they'll be picked up from the `target/classes` folder.

**Comment by freddyboucher** [comment]
Oh I see, thanks!
