### ISSUE TITLE
Unable to compile gwt project

### ISSUE THREAD

**Issue by sameepsi** [tbroyer/gwt-maven-plugin#88]
Hi,
I have created a gwt project through eclipse using maven. When I am trying to compile the project I am getiing following error.
 Finding entry point classes
[INFO]       Tracing compile failure path for type 'test.client.Test'
[INFO]          Checked 0 dependencies for errors.
[INFO]       [ERROR] Hint: Check that the type name 'test.client.Test' is really what you meant
[INFO]       [ERROR] Hint: Check that your classpath includes all required source roots

Failed to execute goal net.ltgt.gwt.maven:gwt-maven-plugin:1.0-rc-6:compile (default-cli) on project Test: GWT Compiler exited with status 1 -> [Help 1]

I have this entry point class and it is correctly mentioned in the gwt.xml

**Comment by TDesjardins** [comment]
Have you checked your classpath?

**Comment by sameepsi** [comment]
yes i have correct classpath

**Comment by tbroyer** [comment]
Can you share the project? Which command did you use to "compile the project"? Can you re-run it with `-X` and share the log?
