### ISSUE TITLE
gwt-maven-plugin not correctly setting the GWT SDK path.

### ISSUE THREAD

**Issue by JRSofty** [tbroyer/gwt-maven-plugin#93]
From what I'm understanding using Eclipse Neon 3 the gwt-maven-plugin should set the GWT SDK properties for the project to use the gwt files located in the Maven .m2 repository. I have a project that I store on SVN. I don't store all the project files just the source files and pom.xml. I usually have to perform a maven update and it all pops in correctly. However, when I checked out the project fresh for a collleague to use they keep getting an error that says the GWT SDK is incorrect the error looks like this.

    The GWT SDK 'C:\Users\<username>\.m2\repository\com\google\gwt' on the project's build path is not valid (Version  is not supported, must be 2.0.0 or later)

When I look in the project's GWT Properties for the SDK setting instead of seeing `C:\Users\<username>\.m2\repository\com\google\gwt - 2.8.1` as I do in my IDE I see `C:\Users\<username>\.m2\repository\com\google\gwt - unknown`

No amount of Maven Updates, or Cleaning seem to fix this problem. The error always returns. How can I fix this so that my colleague can also run and debug the project?

**Comment by tbroyer** [comment]
This is unrelated to the gwt-maven-plugin, and probably unrelated to Maven either.

I would delete the `C:\Users\<username>\.m2\repository\com\google\gwt` folder to force Maven to re-download the artifacts; and check the versions of the GWT Eclipse Plugin (and Eclipse itself too).
If the problem persists, then ask for assistance on the [GWT Users forum](https://groups.google.com/forum/#!forum/google-web-toolkit), but the gwt-maven-plugin itself does not configure Eclipse (the GWT Eclipse Plugin does that, based on the gwt-maven-plugin configuration –or at least its presence– and project dependencies).

That said, ideally, you should be able to run and debug your project using just Maven and your browser dev tools (speaking of client-side debugging here only), such that it doesn't matter which IDE you're using (if any).
