### ISSUE TITLE
wrong default in test includes description

### ISSUE THREAD

**Issue by MCMicS** [tbroyer/gwt-maven-plugin#97]
see https://tbroyer.github.io/gwt-maven-plugin/test-mojo.html#includes

it says: 
```
<includes>
 <include>**/Test*.java</include>
 <include>**/*Test.java</include>
 <include>**/*Tests.java</include>
 <include>**/*TestCase.java</include>
</includes>
```
But only Test Suites are allowed:
see: https://github.com/tbroyer/gwt-maven-plugin/blob/master/src/main/java/net/ltgt/gwt/maven/TestMojo.java
```
@Override
  protected String[] getDefaultIncludes() {
    return new String[] {"**/*Suite.java", "**/*SuiteNoBrowser.java"};
}
```

It confuse the users of the plugin :)

**Comment by tbroyer** [comment]
Thanks for the report; copy-pasta indeed (in this case; I hope there aren't too many other bits of inaccurate documentation that I cannot fix…). Also added a note in the goal description that some doc is inherited from Surefire and cannot be changed.
