### ISSUE TITLE
Recommend an "Automatic-Module-Name" in docs for gwt-lib that wraps foo-core.jar with automatic module name "org.foo.core"

### ISSUE THREAD

**Issue by ge0ffrey** [tbroyer/gwt-maven-plugin#98]
Half of our build needs to be JDK9 friendly. The other half is GWT and less of a concern right now.
To accomplish that, we are adding an "Automatic-Module-Name" entry in all MANIFEST.mf files (even the GWT modules because the multiparent pom does it). That way, we won't break backwards compatibility once we introduce module-info.java files in a later release.

While doing that, we ran into this existential question between this gwt-maven-plugin and JDK 9:
**Given a `foo-core.jar` with module name `org.foo.core` in its pom and given a `gwt-lib` pom called `foo-core-gwt` to wrap that `foo-core.jar`, what should be the module name for that second pom?**

More info:
   https://github.com/kiegroup/optaplanner/pull/349/files#r148462889

**Comment by tbroyer** [comment]
I'll be honest: the way I see JPMS for now is **only** as an annoyance (if not more). I have no idea what it's supposed to bring me that justifies all those breaking changes. As such, I haven't investigated at all.

That being said, I believe this is a matter that's not limited (and actually unrelated) to the use of this plugin (or even Maven), so I'd suggest moving this discussion to the [user group](https://groups.google.com/forum/#!forum/google-web-toolkit).
